package app_test

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"cosmossdk.io/math"

	"github.com/DeBrosOfficial/network/chain/app/params"
	"github.com/DeBrosOfficial/network/chain/reporter"
	emissiontypes "github.com/DeBrosOfficial/network/chain/x/emission/types"
	powertypes "github.com/DeBrosOfficial/network/chain/x/power/types"
	relaytypes "github.com/DeBrosOfficial/network/chain/x/relay/types"
	storagetypes "github.com/DeBrosOfficial/network/chain/x/storage/types"
)

// The "What do I earn" page (website/src/docs/blockchain/what-do-i-earn.mdx) holds tables computed
// from the chain's parameters. This test builds the same tables from the code and requires the page
// to carry them verbatim between its two markers, so a parameter change fails here until the page is
// regenerated. Regenerate with: go test ./app -run TestEarningsPage -update-earnings-page
var updateEarningsPage = flag.Bool("update-earnings-page", false, "rewrite the generated tables of the what-do-i-earn page from the parameters")

const (
	earningsPagePath  = "../../website/src/docs/blockchain/what-do-i-earn.mdx"
	earningsStartMark = "{/* what-do-i-earn:start (generated by chain/app/earnings_page_test.go, do not edit by hand) */}"
	earningsEndMark   = "{/* what-do-i-earn:end */}"

	// The epoch `orama setup --create-network` gives a test network (core/cmd/orama/internal/setup testEpochDuration) and a
	// production epoch (emissiontypes.DefaultEpochDuration).
	stagenetEpoch = 300 * time.Second
)

// orama formats a norama amount as ORAMA with thousands separators and no trailing zeros.
func orama(n math.Int) string {
	unit := math.NewInt(params.NoramaPerOrama)
	whole, frac := n.Quo(unit).String(), n.Mod(unit).Int64()
	var b strings.Builder
	for i, digit := range whole {
		if i > 0 && (len(whole)-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(digit)
	}
	if frac == 0 {
		return b.String()
	}
	return b.String() + strings.TrimRight(fmt.Sprintf(".%09d", frac), "0")
}

// orama3 is orama rounded down to three decimals, for amounts that are not round.
func orama3(n math.Int) string {
	return orama(n.QuoRaw(1_000_000).MulRaw(1_000_000))
}

// grouped formats a whole number with thousands separators.
func grouped(n int64) string { return orama(math.NewInt(n).MulRaw(params.NoramaPerOrama)) }

func fromOrama(whole int64) math.Int { return math.NewInt(whole).MulRaw(params.NoramaPerOrama) }

// percent formats a Dec share as a percentage with up to three decimals.
func percent(d math.LegacyDec) string {
	s := d.MulInt64(100).Mul(math.LegacyNewDec(1000)).TruncateInt().ToLegacyDec().QuoInt64(1000).String()
	s = strings.TrimRight(strings.TrimRight(s, "0"), ".")
	return s + "%"
}

func row(cells ...string) string { return "| " + strings.Join(cells, " | ") + " |\n" }

func table(header []string, rows ...[]string) string {
	sep := make([]string, len(header))
	for i := range sep {
		sep[i] = "---"
	}
	out := row(header...) + row(sep...)
	for _, r := range rows {
		out += row(r...)
	}
	return out
}

// perEpochPools is the first table: what the schedule lets each share pay in one epoch.
func perEpochPools() string {
	var rows [][]string
	for _, b := range []struct {
		label string
		epoch uint64
	}{
		{"1 to 730", 1}, {"731 to 1,460", 731}, {"1,461 to 2,190", 1461}, {"2,191 to 2,920", 2191}, {"2,921 to 3,650", 2921}, {"3,651 onward", 3651},
	} {
		split := emissiontypes.SplitEpochMint(emissiontypes.MaxMintableForEpoch(b.epoch))
		rows = append(rows, []string{b.label, orama(emissiontypes.MaxMintableForEpoch(b.epoch)), orama(split.Validator), orama(split.Storage), orama(split.Relay), orama(split.Development)})
	}
	return table([]string{"Epochs", "Maximum per epoch", "Validators and delegators", "Storage ceiling", "Relay ceiling", "Development ceiling"}, rows...)
}

// validatorShares is the stake scenario of the validator table: 40 operators, one holding 30% of the
// bonded stake, one holding 1%, and the other 38 splitting the remaining 69% equally. The cap is the
// genesis one (types.DefaultParams) and the shares come from ComputeOperatorCappedShares.
func validatorShares() (large, small, rest math.LegacyDec) {
	p := powertypes.DefaultParams()
	const total = 10_000
	stakes := []powertypes.OperatorStake{
		{OperatorAddress: "large", Operator: "large", BondedTokens: math.NewInt(total * 30 / 100)},
		{OperatorAddress: "small", Operator: "small", BondedTokens: math.NewInt(total * 1 / 100)},
	}
	for i := 0; i < 38; i++ {
		name := fmt.Sprintf("op-%02d", i)
		stakes = append(stakes, powertypes.OperatorStake{OperatorAddress: name, Operator: name, BondedTokens: math.NewInt(total * 69 / 100 / 38)})
	}
	shares := powertypes.ComputeOperatorCappedShares(stakes, p.CapFractionNormal, p.MaxRedistributionMultiplier)
	return shares[0], shares[1], shares[2]
}

func validatorTable() string {
	large, small, rest := validatorShares()
	year1 := emissiontypes.SplitEpochMint(emissiontypes.MaxMintableForEpoch(1)).Validator
	tail := emissiontypes.SplitEpochMint(emissiontypes.MaxMintableForEpoch(3651)).Validator
	pay := func(pool math.Int, share math.LegacyDec) string {
		return orama3(share.MulInt(pool).TruncateInt())
	}
	return table(
		[]string{"Operator", "Bonded stake", "Share of stake power", "Epochs 1 to 730, per epoch", "From epoch 3,651, per epoch"},
		[]string{"Large", "30% of all bonded stake", percent(large), pay(year1, large), pay(tail, large)},
		[]string{"Each of 38 average operators", "69% shared equally, about 1.8% each", percent(rest), pay(year1, rest), pay(tail, rest)},
		[]string{"Small", "1% of all bonded stake", percent(small), pay(year1, small), pay(tail, small)},
		[]string{"Zero-stake newcomer", "0", "0%", "0", "0"},
	)
}

func storageTable() string {
	sp := storagetypes.DefaultParams()
	price := fromOrama(1)
	provider := func(slots int64, subsidy math.LegacyDec) math.Int {
		perSlot, _, _ := storagetypes.SplitServicePayment(price)
		fromSubsidy, _, _ := storagetypes.SplitServicePayment(storagetypes.ApplyRate(price, subsidy))
		return perSlot.Add(fromSubsidy).MulRaw(slots)
	}
	none, full := math.LegacyZeroDec(), storagetypes.SMax
	protocol, _, _ := storagetypes.SplitServicePayment(sp.ProtocolPricePerEpoch)
	capEpoch1 := storagetypes.OperatorSubsidyCap(emissiontypes.SplitEpochMint(emissiontypes.MaxMintableForEpoch(1)).Storage, sp.SMinProviders)
	return table(
		[]string{"Provider", "Proved slots paid per epoch", "Paid by a customer deal at 1 ORAMA per slot-epoch, no subsidy", "Same, with the full subsidy"},
		[]string{"Small (one node, one deal)", "1", orama(provider(1, none)), orama(provider(1, full))},
		[]string{"Large (one node at the sample size)", fmt.Sprint(sp.KC), orama(provider(int64(sp.KC), none)), orama(provider(int64(sp.KC), full))},
		[]string{"Zero-stake newcomer on probation, one protocol slot at the protocol price of " + grouped(sp.ProtocolPricePerEpoch.Int64()) + " norama", fmt.Sprint(sp.ProbationSlots), orama(protocol) + " (" + protocol.String() + " norama)", "none: a protocol deal has no subsidy"},
	) + fmt.Sprintf("\nThe subsidy is zero below %d distinct operators and reaches its full value at %d. One operator can collect at most %s ORAMA of subsidy per epoch while the storage ceiling is at its epoch-1 value.\n",
		sp.SMinProviders, sp.SFullProviders, orama(capEpoch1))
}

func relayTable() string {
	rp := relaytypes.DefaultParams()
	gross := func(measured int64, exit bool) math.Int {
		amount := math.NewInt(measured).MulRaw(reporter.NoramaPerWeight)
		if amount.GT(rp.PerRelayCap) {
			amount = rp.PerRelayCap
		}
		if exit {
			amount = math.LegacyNewDecFromInt(amount).Mul(rp.ExitMultiplier).TruncateInt()
		}
		if amount.GT(rp.PerOperatorCap) {
			amount = rp.PerOperatorCap
		}
		return amount
	}
	net := func(g math.Int) string {
		toOperator, _, _ := storagetypes.SplitServicePayment(g)
		return orama(toOperator)
	}
	type relay struct {
		name     string
		measured int64
		exit     bool
	}
	var rows [][]string
	for _, r := range []relay{
		{"Small relay (also what a zero-stake newcomer starts as)", 1_000, false},
		{"Large relay, at the per-relay cap", 100_000, false},
		{"Large exit relay", 100_000, true},
	} {
		g := gross(r.measured, r.exit)
		rows = append(rows, []string{r.name, grouped(r.measured), orama(g), net(g)})
	}
	return table([]string{"Relay", "Measured bandwidth reported", "Settled per epoch", "Credited to earnings (90%)"}, rows...)
}

func perDayTable() string {
	rows := [][]string{
		{"Mainnet", grouped(int64(emissiontypes.DefaultEpochDuration/time.Second)) + " seconds", fmt.Sprint(int(24 * time.Hour / emissiontypes.DefaultEpochDuration))},
		{"Stagenet", grouped(int64(stagenetEpoch/time.Second)) + " seconds", fmt.Sprint(int(24 * time.Hour / stagenetEpoch))},
	}
	return table([]string{"Network", "Epoch length", "Epochs per day"}, rows...)
}

// citation points at the line of the code that sets one number of the tables. The block lists them
// and the test reads each line, so a citation that moved fails here.
type citation struct {
	what     string
	file     string // relative to chain/; "../core/..." is a file of core
	line     int
	contains string
}

var earningsCitations = []citation{
	{"Epoch maximums 14,848 / 7,424 / 3,712 / 1,856 / 928", "x/emission/types/schedule.go", 23, "halvingBracketsOrama"},
	{"730 epochs per bracket", "x/emission/types/schedule.go", 11, "EpochsPerHalvingBracket = 730"},
	{"Tail of 274 per epoch", "x/emission/types/schedule.go", 27, "TailPerEpochOrama = 274"},
	{"Split 60 / 25 / 10 / 5", "x/emission/types/split.go", 16, "ValidatorSharePercent"},
	{"Mainnet epoch of 24 hours", "x/emission/types/params.go", 14, "DefaultEpochDuration"},
	{"Stagenet epoch of 300 seconds", "../core/cmd/orama/internal/setup/create_genesis.go", 24, "testEpochDuration"},
	{"Operator cap of 5%", "x/power/types/params.go", 121, "LegacyNewDecWithPrec(5, 2)"},
	{"Redistribution bound of 2", "x/power/types/params.go", 61, "DefaultMaxRedistributionMultiplier"},
	{"Provider share of a service payment, 90%", "x/storage/types/subsidy.go", 11, "ServiceProviderBPS"},
	{"Sample size of 8 slots per node", "x/storage/types/params.go", 17, "DefaultKC"},
	{"Subsidy starts at 8 operators", "x/storage/types/params.go", 24, "DefaultSMinProviders"},
	{"Subsidy is full at 32 operators", "x/storage/types/params.go", 26, "DefaultSFullProviders"},
	{"One protocol slot per probation node", "x/storage/types/params.go", 30, "DefaultProbationSlots"},
	{"Protocol price of 1,000 norama", "x/storage/types/params.go", 52, "DefaultProtocolPrice"},
	{"Relay quorum of 3 reporters", "x/relay/types/params.go", 14, "DefaultMinReportersQuorum"},
	{"Relay uptime floor of 0.9", "x/relay/types/params.go", 16, "DefaultMinUptimeFraction"},
	{"Exit relays paid twice", "x/relay/types/params.go", 18, "DefaultExitMultiplier"},
	{"Per-relay cap of 100 ORAMA", "x/relay/types/params.go", 22, "DefaultPerRelayCap"},
	{"Per-operator cap of 200 ORAMA", "x/relay/types/params.go", 24, "DefaultPerOperatorCap"},
	{"1,000,000 norama per unit of measured bandwidth", "reporter/observe.go", 20, "NoramaPerWeight"},
}

func citationsTable() string {
	rows := make([][]string, len(earningsCitations))
	for i, c := range earningsCitations {
		path := "chain/" + c.file
		if rest, ok := strings.CutPrefix(c.file, "../"); ok {
			path = rest
		}
		rows[i] = []string{c.what, fmt.Sprintf("`%s:%d`", path, c.line)}
	}
	return table([]string{"Number", "Where it is set"}, rows...)
}

func earningsPageBlock() string {
	return earningsStartMark + "\n\n" +
		"### What each share can pay in one epoch (ORAMA)\n\n" + perEpochPools() + "\n" +
		"### Validators and delegators, per epoch (ORAMA)\n\n" + validatorTable() + "\n" +
		"### Storage providers, per epoch (ORAMA)\n\n" + storageTable() + "\n" +
		"### Relays, per epoch (ORAMA)\n\n" + relayTable() + "\n" +
		"### Epochs per day\n\n" + perDayTable() + "\n" +
		"### Where each number comes from\n\n" + citationsTable() + "\n" +
		earningsEndMark
}

func TestEarningsPage_tablesMatchTheParameters(t *testing.T) {
	want := earningsPageBlock()
	page, err := os.ReadFile(earningsPagePath)
	require.NoError(t, err)
	text := string(page)
	start, end := strings.Index(text, earningsStartMark), strings.Index(text, earningsEndMark)
	require.True(t, start >= 0 && end > start, "the page needs its generated block between %q and %q", earningsStartMark, earningsEndMark)
	end += len(earningsEndMark)

	if *updateEarningsPage {
		require.NoError(t, os.WriteFile(earningsPagePath, []byte(text[:start]+want+text[end:]), 0o644))
		return
	}
	require.Equal(t, want, text[start:end], "the what-do-i-earn tables are out of date with the parameters: run go test ./app -run TestEarningsPage -update-earnings-page")
}

func TestEarningsPage_numbersFollowTheCodeNotTheProse(t *testing.T) {
	// The first row of the first table is epoch 1: 14,848 ORAMA split 60/25/10/5.
	split := emissiontypes.SplitEpochMint(emissiontypes.MaxMintableForEpoch(1))
	require.Equal(t, "8,908.8", orama(split.Validator))
	require.Equal(t, "3,712", orama(split.Storage))
	require.Equal(t, "1,484.8", orama(split.Relay))
	require.Equal(t, "742.4", orama(split.Development))
	require.Equal(t, "0.0000009", orama(math.NewInt(900)))

	// The operator cap binds the large operator and hands the excess to the others.
	large, small, rest := validatorShares()
	require.Equal(t, powertypes.DefaultParams().CapFractionNormal.String(), large.String())
	require.True(t, rest.GT(math.LegacyNewDecWithPrec(1816, 5)), "the redistribution raises each average operator above its raw 1.816%%")
	require.True(t, small.GT(math.LegacyNewDecWithPrec(1, 2)), "the redistribution raises the small operator above its raw 1%%")

	// A relay at the per-relay cap, and the exit relay at the per-operator cap.
	rp := relaytypes.DefaultParams()
	require.Equal(t, "100", orama(rp.PerRelayCap))
	require.Equal(t, "200", orama(rp.PerOperatorCap))
}

func TestEarningsPage_everyCitationStillPointsAtItsNumber(t *testing.T) {
	for _, c := range earningsCitations {
		raw, err := os.ReadFile("../" + c.file)
		require.NoError(t, err, c.what)
		lines := strings.Split(string(raw), "\n")
		require.GreaterOrEqual(t, len(lines), c.line, "%s: %s has %d lines", c.what, c.file, len(lines))
		require.Contains(t, lines[c.line-1], c.contains, "%s: %s:%d moved", c.what, c.file, c.line)
	}
}
