package sshx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net"
	"time"

	"golang.org/x/crypto/ssh"
)

// errKeyCaptured ends a scan handshake once the host key has been read.
var errKeyCaptured = errors.New("host key captured")

// ScanHostKey reads the ssh-ed25519 host key host presents, without
// authenticating: the handshake is abandoned as soon as the key is known.
func ScanHostKey(ctx context.Context, host string) (ssh.PublicKey, error) {
	var got ssh.PublicKey
	cfg := &ssh.ClientConfig{
		User: "scan",
		HostKeyCallback: func(_ string, _ net.Addr, key ssh.PublicKey) error {
			got = key
			return errKeyCaptured
		},
		HostKeyAlgorithms: hostKeyAlgorithms,
		Timeout:           dialTimeout,
	}
	client, err := connect(ctx, address(host), cfg)
	if client != nil {
		client.Close()
	}
	if got != nil {
		return got, nil
	}
	if err == nil {
		return nil, fmt.Errorf("SSH handshake with %s completed without a host key", host)
	}
	return nil, err
}

// ConfirmHostKey polls ScanHostKey every interval until host presents want,
// or ctx ends. It never trusts what it sees: the key was generated by the
// harness and handed to the server before it was created (see the
// provisioner's host key phase), so the only thing to learn is whether the
// server's sshd serves it yet. A different key, from an sshd that started
// before cloud-init installed the pinned one or from anything else answering
// on that address, is never accepted and is named in the error when ctx ends.
func ConfirmHostKey(ctx context.Context, host string, want ssh.PublicKey, interval time.Duration) error {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	// mismatch outlives later scan errors: a foreign key is what matters.
	var last, mismatch error
	for {
		key, err := ScanHostKey(ctx, host)
		if err == nil && bytes.Equal(key.Marshal(), want.Marshal()) {
			return nil
		}
		if err == nil {
			mismatch = fmt.Errorf("%s presented host key %s, not the pinned %s", host, Fingerprint(key), Fingerprint(want))
		}
		last = err
		select {
		case <-ctx.Done():
			return fmt.Errorf("%s never presented the pinned host key %s before the deadline (%v): %w",
				host, Fingerprint(want), errors.Join(mismatch, last), ctx.Err())
		case <-ticker.C:
		}
	}
}

// Fingerprint is key's SHA256:... fingerprint, the form `orama node setup
// --host-key` takes.
func Fingerprint(key ssh.PublicKey) string {
	return ssh.FingerprintSHA256(key)
}
