// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orama/power/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorRampRecord records one validator's stake ramp. activation_epoch is
// the epoch its capped share first became positive. admitted_tokens have
// finished ramping; excess_tokens are a later increase still ramping from
// excess_epoch. An import that dropped these amounts would publish the full
// bond on the next block.
type ValidatorRampRecord struct {
	OperatorAddress string                `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	ActivationEpoch uint64                `protobuf:"varint,2,opt,name=activation_epoch,json=activationEpoch,proto3" json:"activation_epoch,omitempty"`
	AdmittedTokens  cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=admitted_tokens,json=admittedTokens,proto3,customtype=cosmossdk.io/math.Int" json:"admitted_tokens"`
	ExcessTokens    cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=excess_tokens,json=excessTokens,proto3,customtype=cosmossdk.io/math.Int" json:"excess_tokens"`
	ExcessEpoch     uint64                `protobuf:"varint,5,opt,name=excess_epoch,json=excessEpoch,proto3" json:"excess_epoch,omitempty"`
	ExcessEpochSet  bool                  `protobuf:"varint,6,opt,name=excess_epoch_set,json=excessEpochSet,proto3" json:"excess_epoch_set,omitempty"`
	ActivationSet   bool                  `protobuf:"varint,7,opt,name=activation_set,json=activationSet,proto3" json:"activation_set,omitempty"`
}

func (m *ValidatorRampRecord) Reset()         { *m = ValidatorRampRecord{} }
func (m *ValidatorRampRecord) String() string { return proto.CompactTextString(m) }
func (*ValidatorRampRecord) ProtoMessage()    {}
func (*ValidatorRampRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32094a1dc818b7f, []int{0}
}
func (m *ValidatorRampRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorRampRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorRampRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorRampRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorRampRecord.Merge(m, src)
}
func (m *ValidatorRampRecord) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorRampRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorRampRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorRampRecord proto.InternalMessageInfo

func (m *ValidatorRampRecord) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *ValidatorRampRecord) GetActivationEpoch() uint64 {
	if m != nil {
		return m.ActivationEpoch
	}
	return 0
}

func (m *ValidatorRampRecord) GetExcessEpoch() uint64 {
	if m != nil {
		return m.ExcessEpoch
	}
	return 0
}

func (m *ValidatorRampRecord) GetExcessEpochSet() bool {
	if m != nil {
		return m.ExcessEpochSet
	}
	return false
}

func (m *ValidatorRampRecord) GetActivationSet() bool {
	if m != nil {
		return m.ActivationSet
	}
	return false
}

// ValidatorPowerRecord records the CometBFT integer power x/power last
// assigned a validator, so EndBlock can compute the next block's diff
// (added/changed/removed validators) without recomputing history.
type ValidatorPowerRecord struct {
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	CometPower      int64  `protobuf:"varint,2,opt,name=comet_power,json=cometPower,proto3" json:"comet_power,omitempty"`
	// consensus_pubkey is the raw ed25519 pubkey bytes last used in a
	// ValidatorUpdate for this operator (Keeper.LastPubKey), carried in the
	// export so ImportGenesis can rebuild the exact genesis ValidatorUpdate set
	// CometBFT needs, byte-for-byte, without re-deriving it from the bootstrap
	// committee or staking state (security review B6: "return validator
	// updates from the imported PowerRecords").
	ConsensusPubkey []byte `protobuf:"bytes,3,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty"`
}

func (m *ValidatorPowerRecord) Reset()         { *m = ValidatorPowerRecord{} }
func (m *ValidatorPowerRecord) String() string { return proto.CompactTextString(m) }
func (*ValidatorPowerRecord) ProtoMessage()    {}
func (*ValidatorPowerRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32094a1dc818b7f, []int{1}
}
func (m *ValidatorPowerRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorPowerRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorPowerRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorPowerRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorPowerRecord.Merge(m, src)
}
func (m *ValidatorPowerRecord) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorPowerRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorPowerRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorPowerRecord proto.InternalMessageInfo

func (m *ValidatorPowerRecord) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *ValidatorPowerRecord) GetCometPower() int64 {
	if m != nil {
		return m.CometPower
	}
	return 0
}

func (m *ValidatorPowerRecord) GetConsensusPubkey() []byte {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

// CommitteeSelfBondRecord records how much norama x/power has force-bonded
// into a bootstrap committee member's own self-delegation so far
// (Params.force_bond_fraction), so the self_bond_cap_multiplier ceiling can
// be checked without re-deriving it from delegation history.
type CommitteeSelfBondRecord struct {
	OperatorAddress string                `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	ForceBonded     cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=force_bonded,json=forceBonded,proto3,customtype=cosmossdk.io/math.Int" json:"force_bonded"`
}

func (m *CommitteeSelfBondRecord) Reset()         { *m = CommitteeSelfBondRecord{} }
func (m *CommitteeSelfBondRecord) String() string { return proto.CompactTextString(m) }
func (*CommitteeSelfBondRecord) ProtoMessage()    {}
func (*CommitteeSelfBondRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32094a1dc818b7f, []int{2}
}
func (m *CommitteeSelfBondRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommitteeSelfBondRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommitteeSelfBondRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommitteeSelfBondRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitteeSelfBondRecord.Merge(m, src)
}
func (m *CommitteeSelfBondRecord) XXX_Size() int {
	return m.Size()
}
func (m *CommitteeSelfBondRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitteeSelfBondRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CommitteeSelfBondRecord proto.InternalMessageInfo

func (m *CommitteeSelfBondRecord) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

// GenesisState is x/power's genesis state.
type GenesisState struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// bootstrap_committee is the fixed genesis committee (plans/open-network.md
	// D16). Must have at least params.min_committee_size members.
	BootstrapCommittee []BootstrapMember `protobuf:"bytes,2,rep,name=bootstrap_committee,json=bootstrapCommittee,proto3" json:"bootstrap_committee"`
	// lambda is the current hand-over factor (0 at a fresh genesis).
	Lambda cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=lambda,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"lambda"`
	// lambda_last_updated_epoch is the epoch lambda was last recomputed at.
	LambdaLastUpdatedEpoch uint64 `protobuf:"varint,4,opt,name=lambda_last_updated_epoch,json=lambdaLastUpdatedEpoch,proto3" json:"lambda_last_updated_epoch,omitempty"`
	// current_cap_bps is the active per-validator cap, in basis points (500 =
	// 5%, 300 = 3%).
	CurrentCapBps uint64 `protobuf:"varint,5,opt,name=current_cap_bps,json=currentCapBps,proto3" json:"current_cap_bps,omitempty"`
	// below_step_up_streak_epochs counts consecutive epochs the active
	// validator count has stayed below params.cap_step_up_validator_count
	// while at the reduced cap (Params.cap_hysteresis_epochs).
	BelowStepUpStreakEpochs uint64 `protobuf:"varint,6,opt,name=below_step_up_streak_epochs,json=belowStepUpStreakEpochs,proto3" json:"below_step_up_streak_epochs,omitempty"`
	// genesis_epoch is the x/emission epoch number in progress when this chain
	// incarnation's genesis ran; epochs_since_genesis for lambda's time-based
	// term is measured from it.
	GenesisEpoch uint64 `protobuf:"varint,7,opt,name=genesis_epoch,json=genesisEpoch,proto3" json:"genesis_epoch,omitempty"`
	// ramp_records is the exported set of ValidatorRampRecord entries.
	RampRecords []ValidatorRampRecord `protobuf:"bytes,8,rep,name=ramp_records,json=rampRecords,proto3" json:"ramp_records"`
	// power_records is the exported set of ValidatorPowerRecord entries (the
	// last CometBFT power x/power assigned each validator).
	PowerRecords []ValidatorPowerRecord `protobuf:"bytes,9,rep,name=power_records,json=powerRecords,proto3" json:"power_records"`
	// committee_self_bonds is the exported set of CommitteeSelfBondRecord
	// entries.
	CommitteeSelfBonds []CommitteeSelfBondRecord `protobuf:"bytes,10,rep,name=committee_self_bonds,json=committeeSelfBonds,proto3" json:"committee_self_bonds"`
	// exported is true for a genesis produced by ExportGenesis to continue an
	// existing chain (e.g. across a coordinated hard fork), and false for a
	// true fresh genesis - mirroring stock x/staking's own GenesisState.exported
	// field and flag (security review B6). On an exported genesis,
	// InitGenesis: does not recompute genesis_epoch from x/emission (it trusts
	// the given value, since epochs_since_genesis must keep counting from the
	// ORIGINAL genesis, not this restart); does not recreate a committee
	// member's staking validator record if one already exists (staking's own
	// InitGenesis, which runs first, already restored it with its real
	// accumulated tokens - creating a fresh zero-token one over it would erase
	// real force-bonded stake); and returns ValidatorUpdates built directly
	// from the imported power_records rather than the genesis equal-bootstrap-share
	// calculation, which only describes a true fresh genesis.
	Exported bool `protobuf:"varint,11,opt,name=exported,proto3" json:"exported,omitempty"`
	// gate_satisfied records whether the handover safety gate has ever been
	// satisfied (security review H3a) - a one-way ratchet once true. Exported
	// and restored so an import never re-opens a gate an earlier run already
	// closed.
	GateSatisfied bool `protobuf:"varint,12,opt,name=gate_satisfied,json=gateSatisfied,proto3" json:"gate_satisfied,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e32094a1dc818b7f, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetBootstrapCommittee() []BootstrapMember {
	if m != nil {
		return m.BootstrapCommittee
	}
	return nil
}

func (m *GenesisState) GetLambdaLastUpdatedEpoch() uint64 {
	if m != nil {
		return m.LambdaLastUpdatedEpoch
	}
	return 0
}

func (m *GenesisState) GetCurrentCapBps() uint64 {
	if m != nil {
		return m.CurrentCapBps
	}
	return 0
}

func (m *GenesisState) GetBelowStepUpStreakEpochs() uint64 {
	if m != nil {
		return m.BelowStepUpStreakEpochs
	}
	return 0
}

func (m *GenesisState) GetGenesisEpoch() uint64 {
	if m != nil {
		return m.GenesisEpoch
	}
	return 0
}

func (m *GenesisState) GetRampRecords() []ValidatorRampRecord {
	if m != nil {
		return m.RampRecords
	}
	return nil
}

func (m *GenesisState) GetPowerRecords() []ValidatorPowerRecord {
	if m != nil {
		return m.PowerRecords
	}
	return nil
}

func (m *GenesisState) GetCommitteeSelfBonds() []CommitteeSelfBondRecord {
	if m != nil {
		return m.CommitteeSelfBonds
	}
	return nil
}

func (m *GenesisState) GetExported() bool {
	if m != nil {
		return m.Exported
	}
	return false
}

func (m *GenesisState) GetGateSatisfied() bool {
	if m != nil {
		return m.GateSatisfied
	}
	return false
}

func init() {
	proto.RegisterType((*ValidatorRampRecord)(nil), "orama.power.v1.ValidatorRampRecord")
	proto.RegisterType((*ValidatorPowerRecord)(nil), "orama.power.v1.ValidatorPowerRecord")
	proto.RegisterType((*CommitteeSelfBondRecord)(nil), "orama.power.v1.CommitteeSelfBondRecord")
	proto.RegisterType((*GenesisState)(nil), "orama.power.v1.GenesisState")
}

func init() { proto.RegisterFile("orama/power/v1/genesis.proto", fileDescriptor_e32094a1dc818b7f) }

var fileDescriptor_e32094a1dc818b7f = []byte{
	// 786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0x26, 0x6e, 0x9a, 0x8e, 0xed, 0xb8, 0xda, 0x86, 0x76, 0x49, 0xc1, 0x09, 0x09, 0x3f,
	0xcc, 0xc5, 0xab, 0x16, 0x38, 0x20, 0x38, 0xc0, 0xb6, 0x80, 0x90, 0x82, 0x12, 0xad, 0x69, 0x0f,
	0x5c, 0x46, 0xb3, 0xb3, 0xcf, 0xce, 0xca, 0xde, 0x9d, 0xd1, 0xbc, 0x71, 0x7e, 0xfc, 0x03, 0xdc,
	0x90, 0xf8, 0xb3, 0x7a, 0xec, 0x11, 0x71, 0xa8, 0x50, 0x72, 0xe4, 0x9f, 0x40, 0xfb, 0x66, 0xbc,
	0x31, 0x86, 0x0a, 0x7a, 0xdb, 0xfd, 0xde, 0xf7, 0xbe, 0x79, 0xf3, 0xcd, 0x37, 0xc3, 0xde, 0x51,
	0x46, 0x94, 0x22, 0xd6, 0xea, 0x1c, 0x4c, 0x7c, 0xf6, 0x28, 0x9e, 0x40, 0x05, 0x58, 0xe0, 0x50,
	0x1b, 0x65, 0x55, 0xb8, 0x4d, 0xd5, 0x21, 0x55, 0x87, 0x67, 0x8f, 0x76, 0x77, 0x26, 0x6a, 0xa2,
	0xa8, 0x14, 0xd7, 0x5f, 0x8e, 0xb5, 0xbb, 0xbb, 0xa2, 0xe1, 0xe8, 0x54, 0x3b, 0xf8, 0x73, 0x9d,
	0xdd, 0x7b, 0x2e, 0x66, 0x45, 0x2e, 0xac, 0x32, 0xa9, 0x28, 0x75, 0x0a, 0x52, 0x99, 0x3c, 0xfc,
	0x98, 0xdd, 0x55, 0x1a, 0x4c, 0x8d, 0x72, 0x91, 0xe7, 0x06, 0x10, 0xa3, 0x60, 0x3f, 0x18, 0xdc,
	0x49, 0x7b, 0x0b, 0xfc, 0x6b, 0x07, 0xd7, 0x54, 0x21, 0x6d, 0x71, 0x26, 0x6c, 0xa1, 0x2a, 0x0e,
	0x5a, 0xc9, 0xd3, 0x68, 0x7d, 0x3f, 0x18, 0xb4, 0xd2, 0xde, 0x0d, 0xfe, 0x4d, 0x0d, 0x87, 0xdf,
	0xb2, 0x9e, 0xc8, 0xcb, 0xc2, 0x5a, 0xc8, 0xb9, 0x55, 0x53, 0xa8, 0x30, 0xda, 0xa8, 0x45, 0x93,
	0x77, 0x5f, 0xbc, 0xda, 0x5b, 0xfb, 0xfd, 0xd5, 0xde, 0x5b, 0x52, 0x61, 0xa9, 0x10, 0xf3, 0xe9,
	0xb0, 0x50, 0x71, 0x29, 0xec, 0xe9, 0xf0, 0xfb, 0xca, 0xa6, 0xdb, 0x8b, 0xae, 0x1f, 0xa9, 0x29,
	0x4c, 0x58, 0x17, 0x2e, 0x24, 0x20, 0x2e, 0x54, 0x5a, 0xff, 0x47, 0xa5, 0xe3, 0x7a, 0xbc, 0xc6,
	0x7b, 0xcc, 0xff, 0xfb, 0x91, 0x6f, 0xd1, 0xc8, 0x6d, 0x87, 0xb9, 0x71, 0x07, 0xec, 0xee, 0x32,
	0x85, 0x23, 0xd8, 0x68, 0x73, 0x3f, 0x18, 0x6c, 0xa5, 0xdb, 0x4b, 0xb4, 0x11, 0xd8, 0xf0, 0x03,
	0xb6, 0xbd, 0xe4, 0x41, 0xcd, 0xbb, 0x4d, 0xbc, 0xee, 0x0d, 0x3a, 0x02, 0x7b, 0xf0, 0x4b, 0xc0,
	0x76, 0x1a, 0xb7, 0x4f, 0xea, 0x63, 0x78, 0x73, 0xbb, 0xf7, 0x58, 0x5b, 0xaa, 0x12, 0x2c, 0xa7,
	0x63, 0x24, 0xa7, 0x37, 0x52, 0x46, 0x10, 0x29, 0xd6, 0x5a, 0x52, 0x55, 0x08, 0x15, 0xce, 0x91,
	0xeb, 0x79, 0x36, 0x85, 0x4b, 0x72, 0xb9, 0x93, 0xf6, 0x1a, 0xfc, 0x84, 0xe0, 0x83, 0x9f, 0x03,
	0xf6, 0xe0, 0x89, 0x2a, 0xc9, 0x5b, 0x18, 0xc1, 0x6c, 0x9c, 0xa8, 0x2a, 0x7f, 0xf3, 0x91, 0xbe,
	0x62, 0x9d, 0xb1, 0x32, 0x12, 0x78, 0xa6, 0xaa, 0x1c, 0x72, 0x9a, 0xe9, 0x3f, 0x4f, 0xa3, 0x4d,
	0x2d, 0x09, 0x75, 0x1c, 0x5c, 0xdd, 0x62, 0x9d, 0xef, 0x5c, 0xb4, 0x47, 0x56, 0x58, 0x08, 0x3f,
	0x65, 0x9b, 0x5a, 0x18, 0x51, 0xba, 0x35, 0xdb, 0x8f, 0xef, 0x0f, 0xff, 0x1e, 0xf5, 0xe1, 0x09,
	0x55, 0x93, 0x56, 0xbd, 0x48, 0xea, 0xb9, 0xe1, 0x73, 0x76, 0x2f, 0x53, 0xca, 0xa2, 0x35, 0x42,
	0x73, 0xb9, 0xd8, 0x58, 0xb4, 0xbe, 0xbf, 0x31, 0x68, 0x3f, 0xde, 0x5b, 0x95, 0x48, 0x16, 0xd4,
	0x1f, 0xa0, 0xcc, 0xc0, 0x78, 0xad, 0xb0, 0x51, 0x68, 0x9c, 0x09, 0xbf, 0x60, 0x9b, 0x33, 0x51,
	0x66, 0xb9, 0xf0, 0x71, 0x3d, 0xf4, 0x5b, 0x7b, 0xf8, 0xcf, 0xad, 0x1d, 0xc1, 0x44, 0xc8, 0xcb,
	0xa7, 0x20, 0x53, 0xdf, 0x12, 0x7e, 0xce, 0xde, 0x76, 0x5f, 0x7c, 0x26, 0xd0, 0xf2, 0xb9, 0xce,
	0x45, 0x9d, 0x7f, 0x97, 0xba, 0x16, 0xa5, 0xee, 0xbe, 0x23, 0x1c, 0x09, 0xb4, 0xcf, 0x5c, 0xd9,
	0x05, 0xf0, 0x43, 0xd6, 0x93, 0x73, 0x63, 0xa0, 0xb2, 0x5c, 0x0a, 0xcd, 0x33, 0x8d, 0x3e, 0xa6,
	0x5d, 0x0f, 0x3f, 0x11, 0x3a, 0xd1, 0x18, 0x7e, 0xc9, 0x1e, 0x66, 0x30, 0x53, 0xe7, 0x1c, 0x2d,
	0x68, 0x3e, 0xd7, 0x1c, 0xad, 0x01, 0x31, 0x75, 0x6b, 0x20, 0x65, 0xb6, 0x95, 0x3e, 0x20, 0xca,
	0xc8, 0x82, 0x7e, 0xa6, 0x47, 0x54, 0xa7, 0x45, 0x30, 0x3c, 0x64, 0x5d, 0xff, 0xac, 0xf8, 0xa1,
	0x6e, 0x13, 0xbf, 0xe3, 0x41, 0x37, 0xca, 0x11, 0xeb, 0x18, 0x51, 0x6a, 0x6e, 0x28, 0x1d, 0x18,
	0x6d, 0x91, 0xa7, 0x87, 0xab, 0x9e, 0xfe, 0xcb, 0x5b, 0xe2, 0x7d, 0x6d, 0x9b, 0x06, 0xc1, 0xf0,
	0x98, 0x75, 0xa9, 0xa5, 0x91, 0xbb, 0x43, 0x72, 0xef, 0xbf, 0x56, 0x6e, 0xe9, 0xb2, 0x78, 0xbd,
	0x8e, 0xbe, 0x81, 0x30, 0xe4, 0x6c, 0xa7, 0x39, 0x6f, 0x8e, 0x30, 0x1b, 0x53, 0x16, 0x31, 0x62,
	0xa4, 0xfb, 0xd1, 0xaa, 0xee, 0x6b, 0x42, 0xbf, 0x88, 0x80, 0x5c, 0x2d, 0x63, 0xb8, 0xcb, 0xb6,
	0xe0, 0x42, 0x2b, 0x63, 0x21, 0x8f, 0xda, 0x74, 0xb7, 0x9b, 0xff, 0xfa, 0xf6, 0x4f, 0x84, 0x05,
	0x8e, 0xc2, 0x16, 0x38, 0x2e, 0x20, 0x8f, 0x3a, 0xee, 0xf6, 0xd7, 0xe8, 0x68, 0x01, 0x26, 0xc7,
	0x2f, 0xae, 0xfa, 0xc1, 0xcb, 0xab, 0x7e, 0xf0, 0xc7, 0x55, 0x3f, 0xf8, 0xf5, 0xba, 0xbf, 0xf6,
	0xf2, 0xba, 0xbf, 0xf6, 0xdb, 0x75, 0x7f, 0xed, 0xa7, 0xcf, 0x26, 0x85, 0x3d, 0x9d, 0x67, 0x43,
	0xa9, 0xca, 0xf8, 0x29, 0x24, 0x46, 0xe1, 0xf1, 0x78, 0x5c, 0xc8, 0x42, 0xcc, 0xe2, 0x0a, 0xec,
	0xb9, 0x32, 0xd3, 0x58, 0x9e, 0x8a, 0xa2, 0x8a, 0x2f, 0xfc, 0x2b, 0x6e, 0x2f, 0x35, 0x60, 0xb6,
	0x49, 0x6f, 0xf8, 0x27, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xef, 0xbd, 0x57, 0x14, 0x25, 0x06,
	0x00, 0x00,
}

func (m *ValidatorRampRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorRampRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorRampRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActivationSet {
		i--
		if m.ActivationSet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.ExcessEpochSet {
		i--
		if m.ExcessEpochSet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.ExcessEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ExcessEpoch))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.ExcessTokens.Size()
		i -= size
		if _, err := m.ExcessTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.AdmittedTokens.Size()
		i -= size
		if _, err := m.AdmittedTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.ActivationEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ActivationEpoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorPowerRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorPowerRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorPowerRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsensusPubkey) > 0 {
		i -= len(m.ConsensusPubkey)
		copy(dAtA[i:], m.ConsensusPubkey)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ConsensusPubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CometPower != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CometPower))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CommitteeSelfBondRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommitteeSelfBondRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommitteeSelfBondRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ForceBonded.Size()
		i -= size
		if _, err := m.ForceBonded.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GateSatisfied {
		i--
		if m.GateSatisfied {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.Exported {
		i--
		if m.Exported {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if len(m.CommitteeSelfBonds) > 0 {
		for iNdEx := len(m.CommitteeSelfBonds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitteeSelfBonds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.PowerRecords) > 0 {
		for iNdEx := len(m.PowerRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PowerRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.RampRecords) > 0 {
		for iNdEx := len(m.RampRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RampRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.GenesisEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.GenesisEpoch))
		i--
		dAtA[i] = 0x38
	}
	if m.BelowStepUpStreakEpochs != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BelowStepUpStreakEpochs))
		i--
		dAtA[i] = 0x30
	}
	if m.CurrentCapBps != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CurrentCapBps))
		i--
		dAtA[i] = 0x28
	}
	if m.LambdaLastUpdatedEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LambdaLastUpdatedEpoch))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Lambda.Size()
		i -= size
		if _, err := m.Lambda.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.BootstrapCommittee) > 0 {
		for iNdEx := len(m.BootstrapCommittee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BootstrapCommittee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorRampRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.ActivationEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.ActivationEpoch))
	}
	l = m.AdmittedTokens.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ExcessTokens.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.ExcessEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.ExcessEpoch))
	}
	if m.ExcessEpochSet {
		n += 2
	}
	if m.ActivationSet {
		n += 2
	}
	return n
}

func (m *ValidatorPowerRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.CometPower != 0 {
		n += 1 + sovGenesis(uint64(m.CometPower))
	}
	l = len(m.ConsensusPubkey)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *CommitteeSelfBondRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.ForceBonded.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.BootstrapCommittee) > 0 {
		for _, e := range m.BootstrapCommittee {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Lambda.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LambdaLastUpdatedEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.LambdaLastUpdatedEpoch))
	}
	if m.CurrentCapBps != 0 {
		n += 1 + sovGenesis(uint64(m.CurrentCapBps))
	}
	if m.BelowStepUpStreakEpochs != 0 {
		n += 1 + sovGenesis(uint64(m.BelowStepUpStreakEpochs))
	}
	if m.GenesisEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.GenesisEpoch))
	}
	if len(m.RampRecords) > 0 {
		for _, e := range m.RampRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PowerRecords) > 0 {
		for _, e := range m.PowerRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CommitteeSelfBonds) > 0 {
		for _, e := range m.CommitteeSelfBonds {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Exported {
		n += 2
	}
	if m.GateSatisfied {
		n += 2
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorRampRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorRampRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorRampRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationEpoch", wireType)
			}
			m.ActivationEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdmittedTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AdmittedTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExcessTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExcessTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExcessEpoch", wireType)
			}
			m.ExcessEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExcessEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExcessEpochSet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ExcessEpochSet = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationSet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ActivationSet = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorPowerRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorPowerRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorPowerRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CometPower", wireType)
			}
			m.CometPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CometPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusPubkey = append(m.ConsensusPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommitteeSelfBondRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommitteeSelfBondRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommitteeSelfBondRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForceBonded", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ForceBonded.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootstrapCommittee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BootstrapCommittee = append(m.BootstrapCommittee, BootstrapMember{})
			if err := m.BootstrapCommittee[len(m.BootstrapCommittee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lambda", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Lambda.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaLastUpdatedEpoch", wireType)
			}
			m.LambdaLastUpdatedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LambdaLastUpdatedEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentCapBps", wireType)
			}
			m.CurrentCapBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentCapBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BelowStepUpStreakEpochs", wireType)
			}
			m.BelowStepUpStreakEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BelowStepUpStreakEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisEpoch", wireType)
			}
			m.GenesisEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenesisEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RampRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RampRecords = append(m.RampRecords, ValidatorRampRecord{})
			if err := m.RampRecords[len(m.RampRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PowerRecords = append(m.PowerRecords, ValidatorPowerRecord{})
			if err := m.PowerRecords[len(m.PowerRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitteeSelfBonds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitteeSelfBonds = append(m.CommitteeSelfBonds, CommitteeSelfBondRecord{})
			if err := m.CommitteeSelfBonds[len(m.CommitteeSelfBonds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exported", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exported = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GateSatisfied", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GateSatisfied = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
