// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orama/archive/v1/archive.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params are x/archive's genesis-set parameters
// (plans/open-network/track-c-chain.md C14). There is no authority and no
// MsgUpdateParams: nothing here is an admin key.
type Params struct {
	// retention_window_blocks is how many blocks the 14-day retention window
	// covers. RetainHeight subtracts this from the tip, then never returns a
	// height above the last fully-archived height.
	RetentionWindowBlocks int64 `protobuf:"varint,1,opt,name=retention_window_blocks,json=retentionWindowBlocks,proto3" json:"retention_window_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_05e5b8a7214928c9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRetentionWindowBlocks() int64 {
	if m != nil {
		return m.RetentionWindowBlocks
	}
	return 0
}

// RangeRecord is one height range in the archive registry: bundle CID,
// block-hash Merkle root, replica deal ids, and the archivers who attested
// that root. A range is archived only when archivers of at least 3 distinct
// operators have attested the pinned root and at least 3 distinct active
// ARCHIVE deal ids are recorded.
// The root is pinned by the first attestation; a different root is refused
// and does not count toward this one.
type RangeRecord struct {
	StartHeight int64  `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight   int64  `protobuf:"varint,2,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	BundleCid   string `protobuf:"bytes,3,opt,name=bundle_cid,json=bundleCid,proto3" json:"bundle_cid,omitempty"`
	// bundle_hash is the 32-byte content hash of the bundle. VerifyBundle
	// checks it against this field and checks the block hashes against merkle_root.
	BundleHash []byte   `protobuf:"bytes,4,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	MerkleRoot []byte   `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	DealIds    []string `protobuf:"bytes,6,rep,name=deal_ids,json=dealIds,proto3" json:"deal_ids,omitempty"`
	// archivers are bech32 account addresses, one distinct signer per entry.
	// Each entry attested merkle_root. A signer who submits a different root
	// is not appended.
	Archivers []string `protobuf:"bytes,7,rep,name=archivers,proto3" json:"archivers,omitempty"`
	Archived  bool     `protobuf:"varint,8,opt,name=archived,proto3" json:"archived,omitempty"`
	// operators[i] is the x/nodes operator of archivers[i]. Each operator
	// counts once toward the three attesters, so one operator's many nodes
	// cannot archive a range alone.
	Operators []string `protobuf:"bytes,9,rep,name=operators,proto3" json:"operators,omitempty"`
}

func (m *RangeRecord) Reset()         { *m = RangeRecord{} }
func (m *RangeRecord) String() string { return proto.CompactTextString(m) }
func (*RangeRecord) ProtoMessage()    {}
func (*RangeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_05e5b8a7214928c9, []int{1}
}
func (m *RangeRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RangeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RangeRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RangeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeRecord.Merge(m, src)
}
func (m *RangeRecord) XXX_Size() int {
	return m.Size()
}
func (m *RangeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RangeRecord proto.InternalMessageInfo

func (m *RangeRecord) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *RangeRecord) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *RangeRecord) GetBundleCid() string {
	if m != nil {
		return m.BundleCid
	}
	return ""
}

func (m *RangeRecord) GetBundleHash() []byte {
	if m != nil {
		return m.BundleHash
	}
	return nil
}

func (m *RangeRecord) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *RangeRecord) GetDealIds() []string {
	if m != nil {
		return m.DealIds
	}
	return nil
}

func (m *RangeRecord) GetArchivers() []string {
	if m != nil {
		return m.Archivers
	}
	return nil
}

func (m *RangeRecord) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *RangeRecord) GetOperators() []string {
	if m != nil {
		return m.Operators
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "orama.archive.v1.Params")
	proto.RegisterType((*RangeRecord)(nil), "orama.archive.v1.RangeRecord")
}

func init() { proto.RegisterFile("orama/archive/v1/archive.proto", fileDescriptor_05e5b8a7214928c9) }

var fileDescriptor_05e5b8a7214928c9 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0x31, 0x8f, 0xd3, 0x30,
	0x18, 0x86, 0xeb, 0x2b, 0xf4, 0x12, 0xf7, 0x06, 0x64, 0x09, 0x61, 0x10, 0x84, 0x70, 0x53, 0xa6,
	0x46, 0x27, 0x24, 0x58, 0x51, 0x61, 0x38, 0x26, 0xc0, 0x0b, 0x12, 0x4b, 0xe4, 0xc4, 0xdf, 0xd5,
	0x56, 0x13, 0x7f, 0x95, 0xed, 0x6b, 0xe1, 0x5f, 0xf0, 0x1f, 0xf8, 0x33, 0x8c, 0x37, 0x32, 0xa2,
	0xf6, 0x8f, 0x9c, 0xea, 0xa4, 0xb9, 0xcd, 0xef, 0xf3, 0xbc, 0xef, 0xe2, 0x8f, 0x66, 0xe8, 0x64,
	0x27, 0x4b, 0xe9, 0x1a, 0x6d, 0xb6, 0x50, 0x6e, 0xaf, 0x4e, 0xcf, 0xc5, 0xc6, 0x61, 0x40, 0xf6,
	0x24, 0xfa, 0xc5, 0x09, 0x6e, 0xaf, 0x2e, 0x3f, 0xd0, 0xd9, 0x57, 0xe9, 0x64, 0xe7, 0xd9, 0x3b,
	0xfa, 0xcc, 0x41, 0x00, 0x1b, 0x0c, 0xda, 0x6a, 0x67, 0xac, 0xc2, 0x5d, 0x55, 0xb7, 0xd8, 0xac,
	0x3d, 0x27, 0x39, 0x29, 0xa6, 0xe2, 0xe9, 0xa8, 0xbf, 0x47, 0xbb, 0x8c, 0xf2, 0xf2, 0xcf, 0x19,
	0x9d, 0x0b, 0x69, 0x57, 0x20, 0xa0, 0x41, 0xa7, 0xd8, 0x1b, 0x7a, 0xe1, 0x83, 0x74, 0xa1, 0xd2,
	0x60, 0x56, 0x3a, 0x0c, 0xe3, 0x79, 0x64, 0xd7, 0x11, 0xb1, 0x57, 0x94, 0x82, 0x55, 0xa7, 0xc2,
	0x59, 0x2c, 0xa4, 0x60, 0xd5, 0x83, 0xae, 0x6f, 0xad, 0x6a, 0xa1, 0x6a, 0x8c, 0xe2, 0xd3, 0x9c,
	0x14, 0xa9, 0x48, 0x7b, 0xf2, 0xd1, 0x28, 0xf6, 0x9a, 0xce, 0x07, 0xad, 0xa5, 0xd7, 0xfc, 0x51,
	0x4e, 0x8a, 0x0b, 0x31, 0x2c, 0xae, 0xa5, 0xd7, 0xc7, 0x42, 0x07, 0x6e, 0xdd, 0x42, 0xe5, 0x10,
	0x03, 0x7f, 0xdc, 0x17, 0x7a, 0x24, 0x10, 0x03, 0x7b, 0x4e, 0x13, 0x05, 0xb2, 0xad, 0x8c, 0xf2,
	0x7c, 0x96, 0x4f, 0x8b, 0x54, 0x9c, 0x1f, 0xf3, 0x67, 0xe5, 0xd9, 0x4b, 0x9a, 0x0e, 0xbf, 0xe3,
	0x3c, 0x3f, 0x8f, 0xee, 0x01, 0xb0, 0x17, 0x34, 0x19, 0x82, 0xe2, 0x49, 0x4e, 0x8a, 0x44, 0x8c,
	0xf9, 0xb8, 0xc4, 0x0d, 0x38, 0x19, 0xd0, 0x79, 0x9e, 0xf6, 0xcb, 0x11, 0x2c, 0xbf, 0xfd, 0xdd,
	0x67, 0xe4, 0x6e, 0x9f, 0x91, 0xff, 0xfb, 0x8c, 0xfc, 0x3e, 0x64, 0x93, 0xbb, 0x43, 0x36, 0xf9,
	0x77, 0xc8, 0x26, 0x3f, 0xde, 0xaf, 0x4c, 0xd0, 0xb7, 0xf5, 0xa2, 0xc1, 0xae, 0xfc, 0x04, 0x4b,
	0x87, 0xfe, 0xcb, 0xcd, 0x8d, 0x69, 0x8c, 0x6c, 0x4b, 0x0b, 0x61, 0x87, 0x6e, 0x5d, 0x36, 0x5a,
	0x1a, 0x5b, 0xfe, 0x1c, 0xef, 0x1a, 0x7e, 0x6d, 0xc0, 0xd7, 0xb3, 0x78, 0xd3, 0xb7, 0xf7, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x91, 0xb2, 0xc2, 0xcf, 0xf5, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RetentionWindowBlocks != 0 {
		i = encodeVarintArchive(dAtA, i, uint64(m.RetentionWindowBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RangeRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RangeRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RangeRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Operators) > 0 {
		for iNdEx := len(m.Operators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Operators[iNdEx])
			copy(dAtA[i:], m.Operators[iNdEx])
			i = encodeVarintArchive(dAtA, i, uint64(len(m.Operators[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.Archived {
		i--
		if m.Archived {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.Archivers) > 0 {
		for iNdEx := len(m.Archivers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Archivers[iNdEx])
			copy(dAtA[i:], m.Archivers[iNdEx])
			i = encodeVarintArchive(dAtA, i, uint64(len(m.Archivers[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.DealIds) > 0 {
		for iNdEx := len(m.DealIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DealIds[iNdEx])
			copy(dAtA[i:], m.DealIds[iNdEx])
			i = encodeVarintArchive(dAtA, i, uint64(len(m.DealIds[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BundleHash) > 0 {
		i -= len(m.BundleHash)
		copy(dAtA[i:], m.BundleHash)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.BundleHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BundleCid) > 0 {
		i -= len(m.BundleCid)
		copy(dAtA[i:], m.BundleCid)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.BundleCid)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EndHeight != 0 {
		i = encodeVarintArchive(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.StartHeight != 0 {
		i = encodeVarintArchive(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintArchive(dAtA []byte, offset int, v uint64) int {
	offset -= sovArchive(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RetentionWindowBlocks != 0 {
		n += 1 + sovArchive(uint64(m.RetentionWindowBlocks))
	}
	return n
}

func (m *RangeRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartHeight != 0 {
		n += 1 + sovArchive(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovArchive(uint64(m.EndHeight))
	}
	l = len(m.BundleCid)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = len(m.BundleHash)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	if len(m.DealIds) > 0 {
		for _, s := range m.DealIds {
			l = len(s)
			n += 1 + l + sovArchive(uint64(l))
		}
	}
	if len(m.Archivers) > 0 {
		for _, s := range m.Archivers {
			l = len(s)
			n += 1 + l + sovArchive(uint64(l))
		}
	}
	if m.Archived {
		n += 2
	}
	if len(m.Operators) > 0 {
		for _, s := range m.Operators {
			l = len(s)
			n += 1 + l + sovArchive(uint64(l))
		}
	}
	return n
}

func sovArchive(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozArchive(x uint64) (n int) {
	return sovArchive(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetentionWindowBlocks", wireType)
			}
			m.RetentionWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetentionWindowBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipArchive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArchive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RangeRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RangeRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RangeRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundleCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundleCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundleHash = append(m.BundleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BundleHash == nil {
				m.BundleHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DealIds = append(m.DealIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archivers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Archivers = append(m.Archivers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archived", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Archived = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operators = append(m.Operators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArchive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArchive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipArchive(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthArchive
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupArchive
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthArchive
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthArchive        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowArchive          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupArchive = fmt.Errorf("proto: unexpected end of group")
)
