// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orama/archive/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgAttest is an archiver attestation of one height range.
type MsgAttest struct {
	Archiver    string `protobuf:"bytes,1,opt,name=archiver,proto3" json:"archiver,omitempty"`
	StartHeight int64  `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight   int64  `protobuf:"varint,3,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	BundleCid   string `protobuf:"bytes,4,opt,name=bundle_cid,json=bundleCid,proto3" json:"bundle_cid,omitempty"`
	BundleHash  []byte `protobuf:"bytes,5,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	MerkleRoot  []byte `protobuf:"bytes,6,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	// node_id is the x/nodes node the archiver field is the hot key of. The
	// node must be active with an ARCHIVER role bond.
	NodeId string `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (m *MsgAttest) Reset()         { *m = MsgAttest{} }
func (m *MsgAttest) String() string { return proto.CompactTextString(m) }
func (*MsgAttest) ProtoMessage()    {}
func (*MsgAttest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3a11b0ac4d1840, []int{0}
}
func (m *MsgAttest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttest.Merge(m, src)
}
func (m *MsgAttest) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttest proto.InternalMessageInfo

func (m *MsgAttest) GetArchiver() string {
	if m != nil {
		return m.Archiver
	}
	return ""
}

func (m *MsgAttest) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *MsgAttest) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *MsgAttest) GetBundleCid() string {
	if m != nil {
		return m.BundleCid
	}
	return ""
}

func (m *MsgAttest) GetBundleHash() []byte {
	if m != nil {
		return m.BundleHash
	}
	return nil
}

func (m *MsgAttest) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *MsgAttest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// MsgAttestResponse is the Msg/Attest response.
type MsgAttestResponse struct {
	Archived  bool   `protobuf:"varint,1,opt,name=archived,proto3" json:"archived,omitempty"`
	Attesters uint32 `protobuf:"varint,2,opt,name=attesters,proto3" json:"attesters,omitempty"`
}

func (m *MsgAttestResponse) Reset()         { *m = MsgAttestResponse{} }
func (m *MsgAttestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAttestResponse) ProtoMessage()    {}
func (*MsgAttestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3a11b0ac4d1840, []int{1}
}
func (m *MsgAttestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttestResponse.Merge(m, src)
}
func (m *MsgAttestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttestResponse proto.InternalMessageInfo

func (m *MsgAttestResponse) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *MsgAttestResponse) GetAttesters() uint32 {
	if m != nil {
		return m.Attesters
	}
	return 0
}

// MsgAttachReplicas records replica deal ids for a height range. The signer
// is the archiver. x/archive does not create or pay the deals.
type MsgAttachReplicas struct {
	Archiver    string `protobuf:"bytes,1,opt,name=archiver,proto3" json:"archiver,omitempty"`
	StartHeight int64  `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight   int64  `protobuf:"varint,3,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	// deal_ids are x/storage ARCHIVE deal ids, as decimal strings. Each must be
	// an active ARCHIVE deal.
	DealIds []string `protobuf:"bytes,4,rep,name=deal_ids,json=dealIds,proto3" json:"deal_ids,omitempty"`
	// node_id is the x/nodes node the archiver field is the hot key of.
	NodeId string `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (m *MsgAttachReplicas) Reset()         { *m = MsgAttachReplicas{} }
func (m *MsgAttachReplicas) String() string { return proto.CompactTextString(m) }
func (*MsgAttachReplicas) ProtoMessage()    {}
func (*MsgAttachReplicas) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3a11b0ac4d1840, []int{2}
}
func (m *MsgAttachReplicas) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttachReplicas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttachReplicas.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttachReplicas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttachReplicas.Merge(m, src)
}
func (m *MsgAttachReplicas) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttachReplicas) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttachReplicas.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttachReplicas proto.InternalMessageInfo

func (m *MsgAttachReplicas) GetArchiver() string {
	if m != nil {
		return m.Archiver
	}
	return ""
}

func (m *MsgAttachReplicas) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *MsgAttachReplicas) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *MsgAttachReplicas) GetDealIds() []string {
	if m != nil {
		return m.DealIds
	}
	return nil
}

func (m *MsgAttachReplicas) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// MsgAttachReplicasResponse is the Msg/AttachReplicas response.
type MsgAttachReplicasResponse struct {
	Archived bool   `protobuf:"varint,1,opt,name=archived,proto3" json:"archived,omitempty"`
	Replicas uint32 `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (m *MsgAttachReplicasResponse) Reset()         { *m = MsgAttachReplicasResponse{} }
func (m *MsgAttachReplicasResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAttachReplicasResponse) ProtoMessage()    {}
func (*MsgAttachReplicasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3a11b0ac4d1840, []int{3}
}
func (m *MsgAttachReplicasResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttachReplicasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttachReplicasResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttachReplicasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttachReplicasResponse.Merge(m, src)
}
func (m *MsgAttachReplicasResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttachReplicasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttachReplicasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttachReplicasResponse proto.InternalMessageInfo

func (m *MsgAttachReplicasResponse) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *MsgAttachReplicasResponse) GetReplicas() uint32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

// MsgCreateArchiveDeal opens one protocol ARCHIVE deal for the bundle of a range
// the signer's operator attested, and attaches it to that range. The chain
// chooses the price and the duration; the archiver supplies only the piece
// commitment of the bundle file (the piece/ commitment, not the SHA-256 that
// MsgAttest pins). A range holds at most a fixed number of live deals.
type MsgCreateArchiveDeal struct {
	Archiver    string `protobuf:"bytes,1,opt,name=archiver,proto3" json:"archiver,omitempty"`
	StartHeight int64  `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight   int64  `protobuf:"varint,3,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	// node_id is the x/nodes node the archiver field is the hot key of.
	NodeId          string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PieceRoot       []byte `protobuf:"bytes,5,opt,name=piece_root,json=pieceRoot,proto3" json:"piece_root,omitempty"`
	RealLeafCount   uint64 `protobuf:"varint,6,opt,name=real_leaf_count,json=realLeafCount,proto3" json:"real_leaf_count,omitempty"`
	PaddedLeafCount uint64 `protobuf:"varint,7,opt,name=padded_leaf_count,json=paddedLeafCount,proto3" json:"padded_leaf_count,omitempty"`
	PieceBytes      uint64 `protobuf:"varint,8,opt,name=piece_bytes,json=pieceBytes,proto3" json:"piece_bytes,omitempty"`
}

func (m *MsgCreateArchiveDeal) Reset()         { *m = MsgCreateArchiveDeal{} }
func (m *MsgCreateArchiveDeal) String() string { return proto.CompactTextString(m) }
func (*MsgCreateArchiveDeal) ProtoMessage()    {}
func (*MsgCreateArchiveDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3a11b0ac4d1840, []int{4}
}
func (m *MsgCreateArchiveDeal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateArchiveDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateArchiveDeal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateArchiveDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateArchiveDeal.Merge(m, src)
}
func (m *MsgCreateArchiveDeal) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateArchiveDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateArchiveDeal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateArchiveDeal proto.InternalMessageInfo

func (m *MsgCreateArchiveDeal) GetArchiver() string {
	if m != nil {
		return m.Archiver
	}
	return ""
}

func (m *MsgCreateArchiveDeal) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *MsgCreateArchiveDeal) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *MsgCreateArchiveDeal) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MsgCreateArchiveDeal) GetPieceRoot() []byte {
	if m != nil {
		return m.PieceRoot
	}
	return nil
}

func (m *MsgCreateArchiveDeal) GetRealLeafCount() uint64 {
	if m != nil {
		return m.RealLeafCount
	}
	return 0
}

func (m *MsgCreateArchiveDeal) GetPaddedLeafCount() uint64 {
	if m != nil {
		return m.PaddedLeafCount
	}
	return 0
}

func (m *MsgCreateArchiveDeal) GetPieceBytes() uint64 {
	if m != nil {
		return m.PieceBytes
	}
	return 0
}

// MsgCreateArchiveDealResponse is the Msg/CreateArchiveDeal response.
type MsgCreateArchiveDealResponse struct {
	DealId   uint64 `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	Archived bool   `protobuf:"varint,2,opt,name=archived,proto3" json:"archived,omitempty"`
	Replicas uint32 `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (m *MsgCreateArchiveDealResponse) Reset()         { *m = MsgCreateArchiveDealResponse{} }
func (m *MsgCreateArchiveDealResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateArchiveDealResponse) ProtoMessage()    {}
func (*MsgCreateArchiveDealResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3a11b0ac4d1840, []int{5}
}
func (m *MsgCreateArchiveDealResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateArchiveDealResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateArchiveDealResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateArchiveDealResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateArchiveDealResponse.Merge(m, src)
}
func (m *MsgCreateArchiveDealResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateArchiveDealResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateArchiveDealResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateArchiveDealResponse proto.InternalMessageInfo

func (m *MsgCreateArchiveDealResponse) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *MsgCreateArchiveDealResponse) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *MsgCreateArchiveDealResponse) GetReplicas() uint32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgAttest)(nil), "orama.archive.v1.MsgAttest")
	proto.RegisterType((*MsgAttestResponse)(nil), "orama.archive.v1.MsgAttestResponse")
	proto.RegisterType((*MsgAttachReplicas)(nil), "orama.archive.v1.MsgAttachReplicas")
	proto.RegisterType((*MsgAttachReplicasResponse)(nil), "orama.archive.v1.MsgAttachReplicasResponse")
	proto.RegisterType((*MsgCreateArchiveDeal)(nil), "orama.archive.v1.MsgCreateArchiveDeal")
	proto.RegisterType((*MsgCreateArchiveDealResponse)(nil), "orama.archive.v1.MsgCreateArchiveDealResponse")
}

func init() { proto.RegisterFile("orama/archive/v1/tx.proto", fileDescriptor_fb3a11b0ac4d1840) }

var fileDescriptor_fb3a11b0ac4d1840 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xbd, 0x4e, 0xdc, 0x40,
	0x10, 0xc7, 0xf1, 0xdd, 0x71, 0x77, 0x5e, 0x20, 0x04, 0x2b, 0x12, 0xc6, 0x21, 0xe6, 0x72, 0x91,
	0xd0, 0x89, 0x48, 0xb6, 0x48, 0x8a, 0x48, 0xe9, 0xf8, 0x28, 0x20, 0xca, 0x29, 0x8a, 0xd3, 0xa5,
	0xb1, 0xf6, 0xbc, 0x73, 0xf6, 0x0a, 0xdb, 0x6b, 0xed, 0x2e, 0x04, 0xba, 0x28, 0x4f, 0x90, 0xd7,
	0x48, 0x47, 0x91, 0x87, 0x48, 0x49, 0x99, 0x32, 0x82, 0x82, 0x3e, 0x4f, 0x10, 0x79, 0x6d, 0x8c,
	0xf9, 0xc8, 0xe9, 0x1a, 0xca, 0xfd, 0xcf, 0x6f, 0x76, 0x77, 0xfe, 0x33, 0xbb, 0x68, 0x85, 0x71,
	0x9c, 0x60, 0x17, 0xf3, 0x20, 0xa2, 0x47, 0xe0, 0x1e, 0x6d, 0xba, 0xf2, 0xd8, 0xc9, 0x38, 0x93,
	0xcc, 0x78, 0xac, 0x42, 0x4e, 0x19, 0x72, 0x8e, 0x36, 0xad, 0xe5, 0x80, 0x89, 0x84, 0x09, 0x37,
	0x11, 0x61, 0x4e, 0x26, 0x22, 0x2c, 0xd0, 0xfe, 0x5f, 0x0d, 0xe9, 0x43, 0x11, 0x6e, 0x49, 0x09,
	0x42, 0x1a, 0x16, 0xea, 0x96, 0x49, 0xdc, 0xd4, 0x7a, 0xda, 0x40, 0xf7, 0xaa, 0xb5, 0xf1, 0x1c,
	0xcd, 0x0b, 0x89, 0xb9, 0xf4, 0x23, 0xa0, 0x61, 0x24, 0xcd, 0x46, 0x4f, 0x1b, 0x34, 0xbd, 0x39,
	0xa5, 0xed, 0x29, 0xc9, 0x78, 0x86, 0x10, 0xa4, 0xe4, 0x0a, 0x68, 0x2a, 0x40, 0x87, 0x94, 0x5c,
	0x87, 0x47, 0x87, 0x29, 0x89, 0xc1, 0x0f, 0x28, 0x31, 0x5b, 0x6a, 0x7f, 0xbd, 0x50, 0x76, 0x28,
	0x31, 0xd6, 0xd0, 0x5c, 0x19, 0x8e, 0xb0, 0x88, 0xcc, 0xd9, 0x9e, 0x36, 0x98, 0xf7, 0xca, 0x8c,
	0x3d, 0x2c, 0xa2, 0x1c, 0x48, 0x80, 0x1f, 0xc4, 0xe0, 0x73, 0xc6, 0xa4, 0xd9, 0x2e, 0x80, 0x42,
	0xf2, 0x18, 0x93, 0xc6, 0x32, 0xea, 0xa4, 0x8c, 0x80, 0x4f, 0x89, 0xd9, 0x51, 0xbb, 0xb7, 0xf3,
	0xe5, 0x3e, 0x79, 0xbb, 0xf0, 0xed, 0xf2, 0x74, 0xa3, 0x2a, 0xa5, 0x3f, 0x44, 0x4b, 0x55, 0xcd,
	0x1e, 0x88, 0x8c, 0xa5, 0x02, 0x6a, 0xb5, 0x13, 0x55, 0x7b, 0xb7, 0xaa, 0x9d, 0x18, 0xab, 0x48,
	0xc7, 0x8a, 0x06, 0x2e, 0x54, 0xe1, 0x0b, 0xde, 0xb5, 0xd0, 0xff, 0xa9, 0x5d, 0xed, 0x87, 0x83,
	0xc8, 0x83, 0x2c, 0xa6, 0x01, 0x16, 0x0f, 0xec, 0xe5, 0x0a, 0xea, 0x12, 0xc0, 0xb1, 0x4f, 0x89,
	0x30, 0x5b, 0xbd, 0xe6, 0x40, 0xf7, 0x3a, 0xf9, 0x7a, 0x9f, 0x88, 0xba, 0x0b, 0xb3, 0x93, 0x5c,
	0xf8, 0x84, 0x56, 0xee, 0xdc, 0x7a, 0x2a, 0x37, 0x2c, 0xd4, 0xe5, 0x25, 0x5f, 0x9a, 0x51, 0xad,
	0xfb, 0xa7, 0x0d, 0xf4, 0x64, 0x28, 0xc2, 0x1d, 0x0e, 0x58, 0xc2, 0x56, 0x91, 0xb1, 0x0b, 0x38,
	0x7e, 0x60, 0x3b, 0x6a, 0x35, 0xb7, 0xea, 0x35, 0xe7, 0x79, 0x19, 0x85, 0xa0, 0x1c, 0x99, 0x62,
	0xa6, 0x74, 0xa5, 0xa8, 0x89, 0x59, 0x47, 0x8b, 0x3c, 0xb7, 0x31, 0x06, 0x3c, 0xf6, 0x03, 0x76,
	0x98, 0x16, 0x63, 0xd5, 0xf2, 0x16, 0x72, 0xf9, 0x3d, 0xe0, 0xf1, 0x4e, 0x2e, 0x1a, 0x1b, 0x68,
	0x29, 0xc3, 0x84, 0x00, 0xa9, 0x93, 0x1d, 0x45, 0x2e, 0x16, 0x81, 0x6b, 0x76, 0x0d, 0xcd, 0x15,
	0x47, 0x8e, 0x4e, 0x24, 0x08, 0xb3, 0xab, 0xa8, 0xe2, 0x16, 0xdb, 0xb9, 0x72, 0xbb, 0x0f, 0x0c,
	0xad, 0xde, 0xe7, 0x58, 0xd5, 0x8a, 0x65, 0xd4, 0x29, 0x5b, 0xad, 0x8c, 0x6b, 0x79, 0xed, 0xa2,
	0xd3, 0x37, 0x7a, 0xd4, 0x98, 0xd0, 0xa3, 0xe6, 0xcd, 0x1e, 0xbd, 0xfa, 0xd1, 0x40, 0xcd, 0xa1,
	0x08, 0x8d, 0x77, 0xa8, 0x5d, 0xbe, 0xfb, 0xa7, 0xce, 0xed, 0x1f, 0xc3, 0xa9, 0x1e, 0x88, 0xf5,
	0x62, 0x42, 0xb0, 0xba, 0xe4, 0x08, 0x3d, 0xba, 0x35, 0xff, 0xff, 0x4d, 0xab, 0x41, 0xd6, 0xcb,
	0x29, 0xa0, 0xea, 0x8c, 0x03, 0xb4, 0x74, 0x77, 0xae, 0xd6, 0xef, 0xdd, 0xe1, 0x0e, 0x67, 0x39,
	0xd3, 0x71, 0x57, 0x87, 0x59, 0xb3, 0x5f, 0x2f, 0x4f, 0x37, 0xb4, 0xed, 0x8f, 0xbf, 0xce, 0x6d,
	0xed, 0xec, 0xdc, 0xd6, 0xfe, 0x9c, 0xdb, 0xda, 0xf7, 0x0b, 0x7b, 0xe6, 0xec, 0xc2, 0x9e, 0xf9,
	0x7d, 0x61, 0xcf, 0x7c, 0x7e, 0x13, 0x52, 0x19, 0x1d, 0x8e, 0x9c, 0x80, 0x25, 0xee, 0x2e, 0x6c,
	0x73, 0x26, 0x3e, 0x8c, 0xc7, 0x34, 0xa0, 0x38, 0x76, 0x53, 0x90, 0x5f, 0x18, 0x3f, 0x70, 0x83,
	0x08, 0xd3, 0xd4, 0x3d, 0xae, 0xfe, 0x68, 0x79, 0x92, 0x81, 0x18, 0xb5, 0xd5, 0xcf, 0xfb, 0xfa,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x00, 0x4c, 0x5d, 0xc1, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Attest pins or confirms the bundle CID, content hash and block-hash
	// Merkle root of an inclusive height range.
	Attest(ctx context.Context, in *MsgAttest, opts ...grpc.CallOption) (*MsgAttestResponse, error)
	// AttachReplicas records storage-deal ids for a range. The deals themselves
	// live in x/storage; this message only records their ids.
	AttachReplicas(ctx context.Context, in *MsgAttachReplicas, opts ...grpc.CallOption) (*MsgAttachReplicasResponse, error)
	// CreateArchiveDeal opens a protocol ARCHIVE deal in x/storage for the bundle
	// of an attested range and records it on that range in the same message.
	CreateArchiveDeal(ctx context.Context, in *MsgCreateArchiveDeal, opts ...grpc.CallOption) (*MsgCreateArchiveDealResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Attest(ctx context.Context, in *MsgAttest, opts ...grpc.CallOption) (*MsgAttestResponse, error) {
	out := new(MsgAttestResponse)
	err := c.cc.Invoke(ctx, "/orama.archive.v1.Msg/Attest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AttachReplicas(ctx context.Context, in *MsgAttachReplicas, opts ...grpc.CallOption) (*MsgAttachReplicasResponse, error) {
	out := new(MsgAttachReplicasResponse)
	err := c.cc.Invoke(ctx, "/orama.archive.v1.Msg/AttachReplicas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateArchiveDeal(ctx context.Context, in *MsgCreateArchiveDeal, opts ...grpc.CallOption) (*MsgCreateArchiveDealResponse, error) {
	out := new(MsgCreateArchiveDealResponse)
	err := c.cc.Invoke(ctx, "/orama.archive.v1.Msg/CreateArchiveDeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Attest pins or confirms the bundle CID, content hash and block-hash
	// Merkle root of an inclusive height range.
	Attest(context.Context, *MsgAttest) (*MsgAttestResponse, error)
	// AttachReplicas records storage-deal ids for a range. The deals themselves
	// live in x/storage; this message only records their ids.
	AttachReplicas(context.Context, *MsgAttachReplicas) (*MsgAttachReplicasResponse, error)
	// CreateArchiveDeal opens a protocol ARCHIVE deal in x/storage for the bundle
	// of an attested range and records it on that range in the same message.
	CreateArchiveDeal(context.Context, *MsgCreateArchiveDeal) (*MsgCreateArchiveDealResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Attest(ctx context.Context, req *MsgAttest) (*MsgAttestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attest not implemented")
}
func (*UnimplementedMsgServer) AttachReplicas(ctx context.Context, req *MsgAttachReplicas) (*MsgAttachReplicasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachReplicas not implemented")
}
func (*UnimplementedMsgServer) CreateArchiveDeal(ctx context.Context, req *MsgCreateArchiveDeal) (*MsgCreateArchiveDealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArchiveDeal not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAttest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orama.archive.v1.Msg/Attest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Attest(ctx, req.(*MsgAttest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AttachReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAttachReplicas)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AttachReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orama.archive.v1.Msg/AttachReplicas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AttachReplicas(ctx, req.(*MsgAttachReplicas))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateArchiveDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateArchiveDeal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateArchiveDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orama.archive.v1.Msg/CreateArchiveDeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateArchiveDeal(ctx, req.(*MsgCreateArchiveDeal))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orama.archive.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attest",
			Handler:    _Msg_Attest_Handler,
		},
		{
			MethodName: "AttachReplicas",
			Handler:    _Msg_AttachReplicas_Handler,
		},
		{
			MethodName: "CreateArchiveDeal",
			Handler:    _Msg_CreateArchiveDeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orama/archive/v1/tx.proto",
}

func (m *MsgAttest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BundleHash) > 0 {
		i -= len(m.BundleHash)
		copy(dAtA[i:], m.BundleHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BundleHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BundleCid) > 0 {
		i -= len(m.BundleCid)
		copy(dAtA[i:], m.BundleCid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BundleCid)))
		i--
		dAtA[i] = 0x22
	}
	if m.EndHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Archiver) > 0 {
		i -= len(m.Archiver)
		copy(dAtA[i:], m.Archiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Archiver)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAttestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Attesters != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Attesters))
		i--
		dAtA[i] = 0x10
	}
	if m.Archived {
		i--
		if m.Archived {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAttachReplicas) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttachReplicas) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttachReplicas) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DealIds) > 0 {
		for iNdEx := len(m.DealIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DealIds[iNdEx])
			copy(dAtA[i:], m.DealIds[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.DealIds[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.EndHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Archiver) > 0 {
		i -= len(m.Archiver)
		copy(dAtA[i:], m.Archiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Archiver)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAttachReplicasResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttachReplicasResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttachReplicasResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Replicas != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Replicas))
		i--
		dAtA[i] = 0x10
	}
	if m.Archived {
		i--
		if m.Archived {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateArchiveDeal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateArchiveDeal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateArchiveDeal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PieceBytes != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PieceBytes))
		i--
		dAtA[i] = 0x40
	}
	if m.PaddedLeafCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PaddedLeafCount))
		i--
		dAtA[i] = 0x38
	}
	if m.RealLeafCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RealLeafCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PieceRoot) > 0 {
		i -= len(m.PieceRoot)
		copy(dAtA[i:], m.PieceRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PieceRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x22
	}
	if m.EndHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Archiver) > 0 {
		i -= len(m.Archiver)
		copy(dAtA[i:], m.Archiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Archiver)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateArchiveDealResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateArchiveDealResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateArchiveDealResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Replicas != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Replicas))
		i--
		dAtA[i] = 0x18
	}
	if m.Archived {
		i--
		if m.Archived {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.DealId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DealId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAttest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Archiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartHeight != 0 {
		n += 1 + sovTx(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovTx(uint64(m.EndHeight))
	}
	l = len(m.BundleCid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BundleHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAttestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Archived {
		n += 2
	}
	if m.Attesters != 0 {
		n += 1 + sovTx(uint64(m.Attesters))
	}
	return n
}

func (m *MsgAttachReplicas) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Archiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartHeight != 0 {
		n += 1 + sovTx(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovTx(uint64(m.EndHeight))
	}
	if len(m.DealIds) > 0 {
		for _, s := range m.DealIds {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAttachReplicasResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Archived {
		n += 2
	}
	if m.Replicas != 0 {
		n += 1 + sovTx(uint64(m.Replicas))
	}
	return n
}

func (m *MsgCreateArchiveDeal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Archiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartHeight != 0 {
		n += 1 + sovTx(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovTx(uint64(m.EndHeight))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PieceRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RealLeafCount != 0 {
		n += 1 + sovTx(uint64(m.RealLeafCount))
	}
	if m.PaddedLeafCount != 0 {
		n += 1 + sovTx(uint64(m.PaddedLeafCount))
	}
	if m.PieceBytes != 0 {
		n += 1 + sovTx(uint64(m.PieceBytes))
	}
	return n
}

func (m *MsgCreateArchiveDealResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DealId != 0 {
		n += 1 + sovTx(uint64(m.DealId))
	}
	if m.Archived {
		n += 2
	}
	if m.Replicas != 0 {
		n += 1 + sovTx(uint64(m.Replicas))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAttest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Archiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundleCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundleCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BundleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BundleHash = append(m.BundleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BundleHash == nil {
				m.BundleHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archived", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Archived = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attesters", wireType)
			}
			m.Attesters = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Attesters |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttachReplicas) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttachReplicas: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttachReplicas: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Archiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DealIds = append(m.DealIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttachReplicasResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttachReplicasResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttachReplicasResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archived", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Archived = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			m.Replicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replicas |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateArchiveDeal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateArchiveDeal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateArchiveDeal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Archiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PieceRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PieceRoot = append(m.PieceRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.PieceRoot == nil {
				m.PieceRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealLeafCount", wireType)
			}
			m.RealLeafCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RealLeafCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaddedLeafCount", wireType)
			}
			m.PaddedLeafCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaddedLeafCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PieceBytes", wireType)
			}
			m.PieceBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PieceBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateArchiveDealResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateArchiveDealResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateArchiveDealResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealId", wireType)
			}
			m.DealId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archived", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Archived = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			m.Replicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replicas |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
