syntax = "proto3";
package orama.cnft.v1;

option go_package = "github.com/DeBrosOfficial/network/chain/x/cnft/types";

import "google/api/annotations.proto";
import "gogoproto/gogo.proto";
import "orama/cnft/v1/cnft.proto";

// Query is x/cnft's gRPC query service.
service Query {
  rpc Collection(QueryCollectionRequest) returns (QueryCollectionResponse) {
    option (google.api.http).get = "/orama/cnft/v1/collection/{id}";
  }
  rpc Tree(QueryTreeRequest) returns (QueryTreeResponse) {
    option (google.api.http).get = "/orama/cnft/v1/tree/{id}";
  }
  rpc Decompressed(QueryDecompressedRequest) returns (QueryDecompressedResponse) {
    option (google.api.http).get = "/orama/cnft/v1/decompressed";
  }
  rpc Snapshots(QuerySnapshotsRequest) returns (QuerySnapshotsResponse) {
    option (google.api.http).get = "/orama/cnft/v1/snapshots/{tree_id}";
  }
}

message QueryCollectionRequest {
  uint64 id = 1;
}

message QueryCollectionResponse {
  Collection collection = 1 [(gogoproto.nullable) = false];
}

message QueryTreeRequest {
  uint64 id = 1;
}

message QueryTreeResponse {
  Tree tree = 1 [(gogoproto.nullable) = false];
}

message QueryDecompressedRequest {
  bytes asset_id = 1;
}

message QueryDecompressedResponse {
  DecompressedAsset asset = 1 [(gogoproto.nullable) = false];
}

message QuerySnapshotsRequest {
  uint64 tree_id = 1;
}

message QuerySnapshotsResponse {
  repeated Snapshot snapshots = 1 [(gogoproto.nullable) = false];
}
