// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orama/market/v1/market.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Listing is a buy-now offer for one compressed asset. Royalty is copied from
// the collection at listing time and is not read again at settlement.
type Listing struct {
	Id             uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seller         string                `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	TreeId         uint64                `protobuf:"varint,3,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	LeafIndex      uint32                `protobuf:"varint,4,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	AssetId        []byte                `protobuf:"bytes,5,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Price          cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=price,proto3,customtype=cosmossdk.io/math.Int" json:"price"`
	RoyaltyCreator string                `protobuf:"bytes,7,opt,name=royalty_creator,json=royaltyCreator,proto3" json:"royalty_creator,omitempty"`
	RoyaltyBps     uint32                `protobuf:"varint,8,opt,name=royalty_bps,json=royaltyBps,proto3" json:"royalty_bps,omitempty"`
	CollectionId   uint64                `protobuf:"varint,9,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bcab28ab29a9c9e, []int{0}
}
func (m *Listing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return m.Size()
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Listing) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *Listing) GetTreeId() uint64 {
	if m != nil {
		return m.TreeId
	}
	return 0
}

func (m *Listing) GetLeafIndex() uint32 {
	if m != nil {
		return m.LeafIndex
	}
	return 0
}

func (m *Listing) GetAssetId() []byte {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *Listing) GetRoyaltyCreator() string {
	if m != nil {
		return m.RoyaltyCreator
	}
	return ""
}

func (m *Listing) GetRoyaltyBps() uint32 {
	if m != nil {
		return m.RoyaltyBps
	}
	return 0
}

func (m *Listing) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

// Bid is an escrowed offer against a listing. The coins sit in the market
// module account until the bid is accepted, cancelled, or refunded.
type Bid struct {
	Id        uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ListingId uint64                `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	Bidder    string                `protobuf:"bytes,3,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Amount    cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *Bid) Reset()         { *m = Bid{} }
func (m *Bid) String() string { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()    {}
func (*Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bcab28ab29a9c9e, []int{1}
}
func (m *Bid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bid.Merge(m, src)
}
func (m *Bid) XXX_Size() int {
	return m.Size()
}
func (m *Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Bid proto.InternalMessageInfo

func (m *Bid) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bid) GetListingId() uint64 {
	if m != nil {
		return m.ListingId
	}
	return 0
}

func (m *Bid) GetBidder() string {
	if m != nil {
		return m.Bidder
	}
	return ""
}

func init() {
	proto.RegisterType((*Listing)(nil), "orama.market.v1.Listing")
	proto.RegisterType((*Bid)(nil), "orama.market.v1.Bid")
}

func init() { proto.RegisterFile("orama/market/v1/market.proto", fileDescriptor_1bcab28ab29a9c9e) }

var fileDescriptor_1bcab28ab29a9c9e = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0xd7, 0x69, 0x9b, 0x6d, 0x4c, 0xff, 0x48, 0x16, 0x7f, 0x02, 0xa2, 0xd9, 0x55, 0x39,
	0xb0, 0xa7, 0x58, 0x55, 0x05, 0x0f, 0x10, 0xb8, 0x44, 0x42, 0x02, 0xe5, 0xc8, 0x65, 0xe5, 0xb5,
	0xbd, 0x59, 0x6b, 0x93, 0x4c, 0x64, 0xbb, 0xa5, 0x7b, 0xe6, 0x05, 0x78, 0x0c, 0x1e, 0xa5, 0xc7,
	0x1e, 0x11, 0x87, 0x0a, 0xed, 0xbe, 0x08, 0xb2, 0xe3, 0x8a, 0x03, 0x87, 0xde, 0xfc, 0xfd, 0xe6,
	0x1b, 0x79, 0xe6, 0xd3, 0xe0, 0xd7, 0xa0, 0x59, 0xcb, 0x68, 0xcb, 0xf4, 0x5a, 0x5a, 0x7a, 0x7d,
	0x11, 0x5e, 0x79, 0xaf, 0xc1, 0x02, 0x39, 0xf5, 0xd5, 0x3c, 0xb0, 0xeb, 0x8b, 0x57, 0x4f, 0x6b,
	0xa8, 0xc1, 0xd7, 0xa8, 0x7b, 0x0d, 0xb6, 0xf3, 0x9f, 0x11, 0x1e, 0x7f, 0x52, 0xc6, 0xaa, 0xae,
	0x26, 0x27, 0x38, 0x52, 0x22, 0x45, 0x53, 0x34, 0xdb, 0xaf, 0x22, 0x25, 0xc8, 0x73, 0x1c, 0x1b,
	0xd9, 0x34, 0x52, 0xa7, 0xd1, 0x14, 0xcd, 0x92, 0x2a, 0x28, 0xf2, 0x02, 0x8f, 0xad, 0x96, 0x72,
	0xae, 0x44, 0xba, 0xe7, 0xcd, 0xb1, 0x93, 0xa5, 0x20, 0x67, 0x18, 0x37, 0x92, 0x2d, 0xe7, 0xaa,
	0x13, 0xf2, 0x26, 0xdd, 0x9f, 0xa2, 0xd9, 0x71, 0x95, 0x38, 0x52, 0x3a, 0x40, 0x5e, 0xe2, 0x43,
	0x66, 0x8c, 0xb4, 0xae, 0xf1, 0x60, 0x8a, 0x66, 0x47, 0xd5, 0xd8, 0xeb, 0x52, 0x90, 0x4b, 0x7c,
	0xd0, 0x6b, 0xc5, 0x65, 0x1a, 0xbb, 0x9f, 0x8a, 0xb3, 0xdb, 0xfb, 0xc9, 0xe8, 0xf7, 0xfd, 0xe4,
	0x19, 0x07, 0xd3, 0x82, 0x31, 0x62, 0x9d, 0x2b, 0xa0, 0x2d, 0xb3, 0xab, 0xbc, 0xec, 0x6c, 0x35,
	0x78, 0xc9, 0x5b, 0x7c, 0xaa, 0x61, 0xc3, 0x1a, 0xbb, 0x99, 0x73, 0x2d, 0x99, 0x05, 0x9d, 0x8e,
	0xfd, 0xa0, 0x27, 0x01, 0x7f, 0x18, 0x28, 0x99, 0xe0, 0x27, 0x0f, 0xc6, 0x45, 0x6f, 0xd2, 0x43,
	0x3f, 0x18, 0x0e, 0xa8, 0xe8, 0x0d, 0x79, 0x83, 0x8f, 0x39, 0x34, 0x8d, 0xe4, 0x56, 0x41, 0xe7,
	0xc6, 0x4b, 0xfc, 0x5e, 0x47, 0xff, 0x60, 0x29, 0xce, 0xbf, 0x23, 0xbc, 0x57, 0x28, 0xf1, 0x5f,
	0x4c, 0x6e, 0xeb, 0x21, 0x41, 0xd7, 0x19, 0x79, 0x9e, 0x04, 0x52, 0xfa, 0x14, 0x17, 0x4a, 0x08,
	0xa9, 0x7d, 0x58, 0x49, 0x15, 0x14, 0x79, 0x87, 0x63, 0xd6, 0xc2, 0x55, 0x67, 0x7d, 0x50, 0x8f,
	0xee, 0x1c, 0xcc, 0xc5, 0x97, 0xdb, 0x6d, 0x86, 0xee, 0xb6, 0x19, 0xfa, 0xb3, 0xcd, 0xd0, 0x8f,
	0x5d, 0x36, 0xba, 0xdb, 0x65, 0xa3, 0x5f, 0xbb, 0x6c, 0xf4, 0xf5, 0x7d, 0xad, 0xec, 0xea, 0x6a,
	0x91, 0x73, 0x68, 0xe9, 0x47, 0x59, 0x68, 0x30, 0x9f, 0x97, 0x4b, 0xc5, 0x15, 0x6b, 0x68, 0x27,
	0xed, 0x37, 0xd0, 0x6b, 0xca, 0x57, 0x4c, 0x75, 0xf4, 0xe6, 0xe1, 0x66, 0xec, 0xa6, 0x97, 0x66,
	0x11, 0xfb, 0x4b, 0xb8, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x66, 0x14, 0x80, 0x0e, 0x50, 0x02,
	0x00, 0x00,
}

func (m *Listing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Listing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Listing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CollectionId != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x48
	}
	if m.RoyaltyBps != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.RoyaltyBps))
		i--
		dAtA[i] = 0x40
	}
	if len(m.RoyaltyCreator) > 0 {
		i -= len(m.RoyaltyCreator)
		copy(dAtA[i:], m.RoyaltyCreator)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.RoyaltyCreator)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.LeafIndex != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.LeafIndex))
		i--
		dAtA[i] = 0x20
	}
	if m.TreeId != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.TreeId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Bid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ListingId != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.ListingId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMarket(dAtA []byte, offset int, v uint64) int {
	offset -= sovMarket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Listing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMarket(uint64(m.Id))
	}
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.TreeId != 0 {
		n += 1 + sovMarket(uint64(m.TreeId))
	}
	if m.LeafIndex != 0 {
		n += 1 + sovMarket(uint64(m.LeafIndex))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovMarket(uint64(l))
	l = len(m.RoyaltyCreator)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.RoyaltyBps != 0 {
		n += 1 + sovMarket(uint64(m.RoyaltyBps))
	}
	if m.CollectionId != 0 {
		n += 1 + sovMarket(uint64(m.CollectionId))
	}
	return n
}

func (m *Bid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMarket(uint64(m.Id))
	}
	if m.ListingId != 0 {
		n += 1 + sovMarket(uint64(m.ListingId))
	}
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovMarket(uint64(l))
	return n
}

func sovMarket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMarket(x uint64) (n int) {
	return sovMarket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Listing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Listing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Listing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeId", wireType)
			}
			m.TreeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeafIndex", wireType)
			}
			m.LeafIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeafIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = append(m.AssetId[:0], dAtA[iNdEx:postIndex]...)
			if m.AssetId == nil {
				m.AssetId = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoyaltyCreator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoyaltyCreator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoyaltyBps", wireType)
			}
			m.RoyaltyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoyaltyBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Bid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListingId", wireType)
			}
			m.ListingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ListingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMarket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMarket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMarket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMarket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMarket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMarket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMarket = fmt.Errorf("proto: unexpected end of group")
)
