// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orama/emission/v1/emission.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params are the genesis-only parameters of x/emission. They are set once at
// genesis and are immutable afterward: the module's only Msg (the test-network
// faucet) never writes them, so no transaction can ever change them (see D18 in
// plans/open-network.md: the emission schedule is ossified and can change
// only by hard fork).
type Params struct {
	// epoch_duration_seconds is the minimum amount of BFT time, in seconds,
	// that must have elapsed since the current epoch started before the epoch
	// can close. Must be in (0, 31,536,000] (365 days). Unless
	// allow_bootstrap_stake is set, must additionally be >= 86,400 (24h): see
	// allow_bootstrap_stake below.
	EpochDurationSeconds int64 `protobuf:"varint,1,opt,name=epoch_duration_seconds,json=epochDurationSeconds,proto3" json:"epoch_duration_seconds,omitempty"`
	// min_blocks_per_epoch is the minimum number of blocks that must have been
	// produced since the current epoch started before the epoch can close.
	// Must be in (0, 1e9]. Unless allow_bootstrap_stake is set, must
	// additionally be >= 14,400: see allow_bootstrap_stake below.
	MinBlocksPerEpoch uint64 `protobuf:"varint,2,opt,name=min_blocks_per_epoch,json=minBlocksPerEpoch,proto3" json:"min_blocks_per_epoch,omitempty"`
	// allow_bootstrap_stake permits a non-production genesis (devnet, stagenet
	// or localnet chain IDs only - enforced in Keeper.InitGenesis, not here,
	// since chain ID is not part of Params) to start with a nonzero norama
	// supply, standing in for the not-yet-built C4 bootstrap-committee module.
	// It defaults to false: a normal (including mainnet) genesis must start at
	// exactly zero supply, and InitGenesis rejects any other genesis state.
	//
	// When false, min_blocks_per_epoch and epoch_duration_seconds have the
	// higher production floors above. The 14,400-block / 24h floor is what
	// makes the block count, not the timestamp, the binding brake on how fast
	// an epoch can close: a coalition with less than 2/3 of voting power
	// cannot force 14,400 blocks in under 24h by lying about block timestamps
	// alone (CometBFT requires >1/3 of voting power to sign each block, and a
	// block's timestamp cannot precede its predecessor's), so shortening the
	// epoch requires either genuinely fast, honest block production or a
	// supermajority equivocation - see docs/CHAIN.md.
	AllowBootstrapStake bool `protobuf:"varint,3,opt,name=allow_bootstrap_stake,json=allowBootstrapStake,proto3" json:"allow_bootstrap_stake,omitempty"`
	// faucet_enabled turns on the test-network faucet (Msg.Faucet). It defaults to
	// false and is rejected at genesis unless the chain-id is a non-production
	// one (devnet, stagenet or localnet), so a production chain can never mint
	// through the faucet.
	FaucetEnabled bool `protobuf:"varint,4,opt,name=faucet_enabled,json=faucetEnabled,proto3" json:"faucet_enabled,omitempty"`
	// faucet_max_drip is the most norama one MsgFaucet may mint. Must be positive
	// when faucet_enabled is set.
	FaucetMaxDrip cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=faucet_max_drip,json=faucetMaxDrip,proto3,customtype=cosmossdk.io/math.Int" json:"faucet_max_drip"`
	// faucet_epoch_cap is the most norama the faucet may mint in one emission
	// epoch, across all recipients. Must be at least faucet_max_drip when
	// faucet_enabled is set.
	FaucetEpochCap cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=faucet_epoch_cap,json=faucetEpochCap,proto3,customtype=cosmossdk.io/math.Int" json:"faucet_epoch_cap"`
	// faucet_recipient_cooldown_seconds is the BFT time, in seconds, that must
	// pass between two faucet drips to the same recipient. Zero disables the
	// cooldown.
	FaucetRecipientCooldownSeconds uint64 `protobuf:"varint,7,opt,name=faucet_recipient_cooldown_seconds,json=faucetRecipientCooldownSeconds,proto3" json:"faucet_recipient_cooldown_seconds,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_66c1c1f62a624962, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEpochDurationSeconds() int64 {
	if m != nil {
		return m.EpochDurationSeconds
	}
	return 0
}

func (m *Params) GetMinBlocksPerEpoch() uint64 {
	if m != nil {
		return m.MinBlocksPerEpoch
	}
	return 0
}

func (m *Params) GetAllowBootstrapStake() bool {
	if m != nil {
		return m.AllowBootstrapStake
	}
	return false
}

func (m *Params) GetFaucetEnabled() bool {
	if m != nil {
		return m.FaucetEnabled
	}
	return false
}

func (m *Params) GetFaucetRecipientCooldownSeconds() uint64 {
	if m != nil {
		return m.FaucetRecipientCooldownSeconds
	}
	return 0
}

// EpochState is the mutable bookkeeping state x/emission updates every block.
type EpochState struct {
	// current_epoch is the number of the epoch currently in progress. It is
	// 1-based: current_epoch == 1 immediately after genesis, and increases by
	// exactly one every time an epoch closes, regardless of how much wall-clock
	// time that closure took (missed epochs are never caught up).
	CurrentEpoch uint64 `protobuf:"varint,1,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	// epoch_start_unix_nano is the BFT time, in Unix nanoseconds, at which the
	// current epoch started.
	EpochStartUnixNano int64 `protobuf:"varint,2,opt,name=epoch_start_unix_nano,json=epochStartUnixNano,proto3" json:"epoch_start_unix_nano,omitempty"`
	// blocks_in_epoch is the number of blocks produced since the current epoch
	// started, incremented once per BeginBlock and reset to zero when the
	// epoch closes. It is a relative counter, not an absolute block height, so
	// it stays meaningful across a chain export/re-import at a fresh height
	// (plans/open-network/track-c-chain.md C3's closing rule needs "blocks
	// since the epoch started", not "which absolute height that was").
	BlocksInEpoch uint64 `protobuf:"varint,3,opt,name=blocks_in_epoch,json=blocksInEpoch,proto3" json:"blocks_in_epoch,omitempty"`
	// cumulative_minted is the all-time total of norama minted as the
	// validator/delegator share. It does not include development spends.
	// Storage and relay ceilings are never minted by this module. The
	// development ceiling is minted only by Keeper.MintDevelopmentSpend, and
	// that total is cumulative_development_minted, not this field.
	CumulativeMinted cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=cumulative_minted,json=cumulativeMinted,proto3,customtype=cosmossdk.io/math.Int" json:"cumulative_minted"`
	// cumulative_burned is the all-time total of norama known to have been
	// burned (e.g. by x/slashing's double-sign/downtime burns from the bonded
	// and not-bonded pools). x/emission has no burn path of its own; it learns
	// about burns elsewhere in the chain by reconciling bank supply against
	// genesis_supply + cumulative_minted at the end of every block (see
	// Keeper.ReconcileBurns) and attributing any shortfall to this field.
	CumulativeBurned cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=cumulative_burned,json=cumulativeBurned,proto3,customtype=cosmossdk.io/math.Int" json:"cumulative_burned"`
	// genesis_supply is the norama bank supply observed the moment this chain incarnation's
	// genesis ran, before x/emission minted anything. It is always zero on a normal genesis; it is
	// non-zero only under the devnet-only bootstrap-stake exception (plans/open-network.md D16 and
	// point 4 of this module's task spec), where genesis accounts self-delegate stake before the
	// C4 bootstrap-committee module exists. The supply invariant is
	// supply == genesis_supply + cumulative_minted + cumulative_development_minted
	// + cumulative_service_minted + cumulative_faucet_minted - cumulative_burned.
	GenesisSupply cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=genesis_supply,json=genesisSupply,proto3,customtype=cosmossdk.io/math.Int" json:"genesis_supply"`
	// cumulative_development_minted is the all-time total minted by
	// Keeper.MintDevelopmentSpend. It is not part of the validator schedule
	// check on cumulative_minted. Pruning a CeilingRecord does not reduce it.
	CumulativeDevelopmentMinted cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=cumulative_development_minted,json=cumulativeDevelopmentMinted,proto3,customtype=cosmossdk.io/math.Int" json:"cumulative_development_minted"`
	// cumulative_service_minted is the all-time total minted against the
	// storage and relay ceilings (Keeper.MintStorageService and
	// Keeper.MintRelayReward). Pruning a CeilingRecord does not reduce it.
	CumulativeServiceMinted cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=cumulative_service_minted,json=cumulativeServiceMinted,proto3,customtype=cosmossdk.io/math.Int" json:"cumulative_service_minted"`
	// validator_split_delta is the running sum, over every closed epoch, of
	// (validator share actually minted) - (validator share the canonical 60/25/10/5
	// split would have minted). It is zero until x/houses enacts an emission split
	// and may be negative. cumulative_minted must equal the canonical schedule's
	// cumulative validator mint plus this delta.
	ValidatorSplitDelta cosmossdk_io_math.Int `protobuf:"bytes,9,opt,name=validator_split_delta,json=validatorSplitDelta,proto3,customtype=cosmossdk.io/math.Int" json:"validator_split_delta"`
	// cumulative_faucet_minted is the all-time total of norama minted by the
	// test-network faucet (Msg.Faucet). Always zero on a production chain.
	CumulativeFaucetMinted cosmossdk_io_math.Int `protobuf:"bytes,10,opt,name=cumulative_faucet_minted,json=cumulativeFaucetMinted,proto3,customtype=cosmossdk.io/math.Int" json:"cumulative_faucet_minted"`
	// faucet_epoch_minted is how much of faucet_epoch_cap the faucet has minted
	// in the current epoch. It resets to zero when the epoch closes.
	FaucetEpochMinted cosmossdk_io_math.Int `protobuf:"bytes,11,opt,name=faucet_epoch_minted,json=faucetEpochMinted,proto3,customtype=cosmossdk.io/math.Int" json:"faucet_epoch_minted"`
}

func (m *EpochState) Reset()         { *m = EpochState{} }
func (m *EpochState) String() string { return proto.CompactTextString(m) }
func (*EpochState) ProtoMessage()    {}
func (*EpochState) Descriptor() ([]byte, []int) {
	return fileDescriptor_66c1c1f62a624962, []int{1}
}
func (m *EpochState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochState.Merge(m, src)
}
func (m *EpochState) XXX_Size() int {
	return m.Size()
}
func (m *EpochState) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochState.DiscardUnknown(m)
}

var xxx_messageInfo_EpochState proto.InternalMessageInfo

func (m *EpochState) GetCurrentEpoch() uint64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *EpochState) GetEpochStartUnixNano() int64 {
	if m != nil {
		return m.EpochStartUnixNano
	}
	return 0
}

func (m *EpochState) GetBlocksInEpoch() uint64 {
	if m != nil {
		return m.BlocksInEpoch
	}
	return 0
}

// CeilingRecord is one closed epoch's storage, relay and development
// ceilings, kept so a later module can claim them within the trailing
// window. closeEpoch does not mint storage, relay or development.
// Keeper.MintDevelopmentSpend mints development up to development_ceiling
// minus development_minted. Keeper.MintRelayReward mints relay rewards up to
// relay_ceiling minus relay_minted, into the relay module account.
// Keeper.MintStorageService mints storage payments up to storage_ceiling
// minus storage_minted, into the storage module account. Records older than the trailing window are pruned.
type CeilingRecord struct {
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// storage_ceiling is the unminted maximum available to storage-subsidy and
	// protocol-deal claims for this epoch.
	StorageCeiling cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=storage_ceiling,json=storageCeiling,proto3,customtype=cosmossdk.io/math.Int" json:"storage_ceiling"`
	// relay_ceiling is the unminted maximum available to relay-reward claims
	// for this epoch.
	RelayCeiling cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=relay_ceiling,json=relayCeiling,proto3,customtype=cosmossdk.io/math.Int" json:"relay_ceiling"`
	// development_ceiling is the maximum an approved development spend can
	// mint for this epoch: the schedule's 5% share.
	DevelopmentCeiling cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=development_ceiling,json=developmentCeiling,proto3,customtype=cosmossdk.io/math.Int" json:"development_ceiling"`
	// validator_minted is the amount actually minted for this epoch's
	// validator/delegator share, including any remainder from integer division
	// of the other shares.
	ValidatorMinted cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=validator_minted,json=validatorMinted,proto3,customtype=cosmossdk.io/math.Int" json:"validator_minted"`
	// development_minted is how much of development_ceiling
	// Keeper.MintDevelopmentSpend has already minted. It starts at zero when
	// the epoch closes and never exceeds development_ceiling.
	DevelopmentMinted cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=development_minted,json=developmentMinted,proto3,customtype=cosmossdk.io/math.Int" json:"development_minted"`
	// relay_minted is how much of relay_ceiling Keeper.MintRelayReward has
	// already minted. It starts at zero when the epoch closes and never
	// exceeds relay_ceiling.
	RelayMinted cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=relay_minted,json=relayMinted,proto3,customtype=cosmossdk.io/math.Int" json:"relay_minted"`
	// storage_minted is how much of storage_ceiling Keeper.MintStorageService
	// has already minted. It never exceeds storage_ceiling.
	StorageMinted cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=storage_minted,json=storageMinted,proto3,customtype=cosmossdk.io/math.Int" json:"storage_minted"`
	// validator_percent, storage_percent, relay_percent and development_percent
	// are the split this epoch closed under (x/houses' enacted split, or the
	// canonical 60/25/10/5). All four zero means the canonical split, so
	// records written before a split could be enacted stay valid.
	ValidatorPercent   uint32 `protobuf:"varint,9,opt,name=validator_percent,json=validatorPercent,proto3" json:"validator_percent,omitempty"`
	StoragePercent     uint32 `protobuf:"varint,10,opt,name=storage_percent,json=storagePercent,proto3" json:"storage_percent,omitempty"`
	RelayPercent       uint32 `protobuf:"varint,11,opt,name=relay_percent,json=relayPercent,proto3" json:"relay_percent,omitempty"`
	DevelopmentPercent uint32 `protobuf:"varint,12,opt,name=development_percent,json=developmentPercent,proto3" json:"development_percent,omitempty"`
}

func (m *CeilingRecord) Reset()         { *m = CeilingRecord{} }
func (m *CeilingRecord) String() string { return proto.CompactTextString(m) }
func (*CeilingRecord) ProtoMessage()    {}
func (*CeilingRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_66c1c1f62a624962, []int{2}
}
func (m *CeilingRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CeilingRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CeilingRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CeilingRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CeilingRecord.Merge(m, src)
}
func (m *CeilingRecord) XXX_Size() int {
	return m.Size()
}
func (m *CeilingRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CeilingRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CeilingRecord proto.InternalMessageInfo

func (m *CeilingRecord) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *CeilingRecord) GetValidatorPercent() uint32 {
	if m != nil {
		return m.ValidatorPercent
	}
	return 0
}

func (m *CeilingRecord) GetStoragePercent() uint32 {
	if m != nil {
		return m.StoragePercent
	}
	return 0
}

func (m *CeilingRecord) GetRelayPercent() uint32 {
	if m != nil {
		return m.RelayPercent
	}
	return 0
}

func (m *CeilingRecord) GetDevelopmentPercent() uint32 {
	if m != nil {
		return m.DevelopmentPercent
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "orama.emission.v1.Params")
	proto.RegisterType((*EpochState)(nil), "orama.emission.v1.EpochState")
	proto.RegisterType((*CeilingRecord)(nil), "orama.emission.v1.CeilingRecord")
}

func init() { proto.RegisterFile("orama/emission/v1/emission.proto", fileDescriptor_66c1c1f62a624962) }

var fileDescriptor_66c1c1f62a624962 = []byte{
	// 842 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xdf, 0x6e, 0x23, 0x35,
	0x14, 0xc6, 0x3b, 0x64, 0xdb, 0xdd, 0x3d, 0x6d, 0xb6, 0x8d, 0xdb, 0x2e, 0x01, 0xb4, 0xd9, 0xd0,
	0x15, 0x50, 0x09, 0x29, 0xa3, 0x02, 0x17, 0x5c, 0xa2, 0x34, 0x5d, 0x28, 0xa2, 0x4b, 0x99, 0x08,
	0x21, 0xb8, 0xb1, 0x1c, 0x8f, 0x9b, 0x5a, 0x99, 0xb1, 0x47, 0xb6, 0x27, 0x4d, 0xdf, 0x82, 0x77,
	0x40, 0xbc, 0xcb, 0xde, 0x20, 0xed, 0x25, 0xe2, 0x62, 0x85, 0xda, 0x17, 0x41, 0xf1, 0x9f, 0xcc,
	0x2c, 0x20, 0xed, 0xf4, 0x6e, 0xea, 0xf3, 0x7d, 0x3f, 0xdb, 0xdf, 0xf1, 0x51, 0x03, 0x7d, 0xa9,
	0x48, 0x4e, 0x62, 0x96, 0x73, 0xad, 0xb9, 0x14, 0xf1, 0xfc, 0x68, 0xf5, 0x3d, 0x28, 0x94, 0x34,
	0x12, 0x75, 0xac, 0x62, 0xb0, 0x5a, 0x9d, 0x1f, 0xbd, 0xbf, 0x37, 0x95, 0x53, 0x69, 0xab, 0xf1,
	0xf2, 0xcb, 0x09, 0x0f, 0x7e, 0x6f, 0xc1, 0xc6, 0x39, 0x51, 0x24, 0xd7, 0xe8, 0x0b, 0x78, 0xcc,
	0x0a, 0x49, 0x2f, 0x71, 0x5a, 0x2a, 0x62, 0xb8, 0x14, 0x58, 0x33, 0x2a, 0x45, 0xaa, 0xbb, 0x51,
	0x3f, 0x3a, 0x6c, 0x25, 0x7b, 0xb6, 0x3a, 0xf2, 0xc5, 0xb1, 0xab, 0xa1, 0x18, 0xf6, 0x72, 0x2e,
	0xf0, 0x24, 0x93, 0x74, 0xa6, 0x71, 0xc1, 0x14, 0xb6, 0xb2, 0xee, 0x3b, 0xfd, 0xe8, 0xf0, 0x5e,
	0xd2, 0xc9, 0xb9, 0x18, 0xda, 0xd2, 0x39, 0x53, 0x27, 0xcb, 0x02, 0xfa, 0x0c, 0xf6, 0x49, 0x96,
	0xc9, 0x2b, 0x3c, 0x91, 0xd2, 0x68, 0xa3, 0x48, 0x81, 0xb5, 0x21, 0x33, 0xd6, 0x6d, 0xf5, 0xa3,
	0xc3, 0x07, 0xc9, 0xae, 0x2d, 0x0e, 0x43, 0x6d, 0xbc, 0x2c, 0xa1, 0x8f, 0xe0, 0xd1, 0x05, 0x29,
	0x29, 0x33, 0x98, 0x09, 0x32, 0xc9, 0x58, 0xda, 0xbd, 0x67, 0xc5, 0x6d, 0xb7, 0x7a, 0xe2, 0x16,
	0xd1, 0x09, 0x6c, 0x7b, 0x59, 0x4e, 0x16, 0x38, 0x55, 0xbc, 0xe8, 0xae, 0xf7, 0xa3, 0xc3, 0x87,
	0xc3, 0x27, 0x2f, 0x5f, 0x3f, 0x5d, 0xfb, 0xeb, 0xf5, 0xd3, 0x7d, 0x2a, 0x75, 0x2e, 0xb5, 0x4e,
	0x67, 0x03, 0x2e, 0xe3, 0x9c, 0x98, 0xcb, 0xc1, 0xa9, 0x30, 0x01, 0x73, 0x46, 0x16, 0x23, 0xc5,
	0x0b, 0xf4, 0x35, 0xec, 0x84, 0xdd, 0x6c, 0x1e, 0x94, 0x14, 0xdd, 0x8d, 0x26, 0x1c, 0x7f, 0x48,
	0x7b, 0xcf, 0x63, 0x52, 0xa0, 0x53, 0xf8, 0xd0, 0x83, 0x14, 0xa3, 0xbc, 0xe0, 0x4c, 0x18, 0x4c,
	0xa5, 0xcc, 0x52, 0x79, 0x55, 0x85, 0x7b, 0xdf, 0x06, 0xd5, 0x73, 0xc2, 0x24, 0xe8, 0x8e, 0xbd,
	0xcc, 0xc7, 0x7c, 0xf0, 0xdb, 0x06, 0x80, 0xe5, 0x8e, 0x0d, 0x31, 0x0c, 0x3d, 0x83, 0x36, 0x2d,
	0x95, 0x5a, 0x02, 0x5d, 0xdc, 0x91, 0xa5, 0x6c, 0xf9, 0x45, 0x97, 0xf4, 0x11, 0xec, 0xbb, 0x0b,
	0x68, 0x43, 0x94, 0xc1, 0xa5, 0xe0, 0x0b, 0x2c, 0x88, 0x90, 0xb6, 0x37, 0xad, 0x04, 0x31, 0xcf,
	0x53, 0xe6, 0x47, 0xc1, 0x17, 0x2f, 0x88, 0x90, 0xe8, 0x63, 0xd8, 0xf6, 0x9d, 0xe4, 0xc2, 0x93,
	0x5b, 0x96, 0xdc, 0x76, 0xcb, 0xa7, 0xc2, 0xa1, 0xbf, 0x85, 0x0e, 0x2d, 0xf3, 0x32, 0x23, 0x86,
	0xcf, 0x19, 0xce, 0xb9, 0x30, 0xbe, 0x27, 0x6f, 0xcd, 0x68, 0xa7, 0xf2, 0x9d, 0x59, 0xdb, 0xbf,
	0x58, 0x93, 0x52, 0x09, 0x96, 0x36, 0xeb, 0x5b, 0x8d, 0x35, 0xb4, 0x36, 0x34, 0x82, 0x47, 0x53,
	0x26, 0x98, 0xe6, 0x1a, 0xeb, 0xb2, 0x28, 0xb2, 0xeb, 0x66, 0x8d, 0x6b, 0x7b, 0xd3, 0xd8, 0x7a,
	0x10, 0x81, 0x27, 0xb5, 0x13, 0xa5, 0x6c, 0xce, 0x32, 0x59, 0xe4, 0xcb, 0xb0, 0xfd, 0x4d, 0xef,
	0x37, 0x81, 0x7e, 0x50, 0x31, 0x46, 0x15, 0xc2, 0x5f, 0xfa, 0x67, 0x78, 0xaf, 0xb6, 0x85, 0x66,
	0x6a, 0xce, 0xe9, 0x2a, 0xc8, 0x07, 0x4d, 0xf0, 0xef, 0x56, 0xfe, 0xb1, 0xb3, 0x7b, 0xf4, 0x0f,
	0xb0, 0x3f, 0x27, 0x19, 0x4f, 0x89, 0x91, 0x0a, 0xeb, 0x22, 0xe3, 0x06, 0xa7, 0x2c, 0x33, 0xa4,
	0xfb, 0xb0, 0x09, 0x76, 0x77, 0xe5, 0x1d, 0x2f, 0xad, 0xa3, 0xa5, 0x13, 0xfd, 0x04, 0xdd, 0xda,
	0x69, 0xc3, 0x8c, 0xb9, 0xc3, 0x42, 0x13, 0xea, 0xe3, 0xca, 0xfe, 0xdc, 0xcd, 0x9a, 0x3b, 0xeb,
	0x19, 0xec, 0xbe, 0x31, 0x6a, 0x9e, 0xb9, 0xd9, 0x84, 0xd9, 0xa9, 0x4d, 0x9b, 0xc3, 0x1d, 0xfc,
	0xb1, 0x0e, 0xed, 0x63, 0xc6, 0x33, 0x2e, 0xa6, 0x09, 0xa3, 0x52, 0xa5, 0x68, 0x0f, 0xd6, 0xeb,
	0x03, 0xe2, 0xfe, 0x40, 0xcf, 0x61, 0x5b, 0x1b, 0xa9, 0xc8, 0x94, 0x61, 0xea, 0xe4, 0x76, 0x26,
	0xde, 0x3e, 0xe0, 0xde, 0xe5, 0xf7, 0x40, 0x43, 0x68, 0x2b, 0x96, 0x91, 0xeb, 0x15, 0xa5, 0xd5,
	0x84, 0xb2, 0x65, 0x3d, 0x81, 0xf1, 0x02, 0x76, 0xeb, 0x2f, 0x2c, 0x90, 0x1a, 0x0d, 0x13, 0xaa,
	0x39, 0x03, 0xef, 0x1b, 0xd8, 0xa9, 0xda, 0xef, 0xf3, 0x6c, 0x34, 0x4d, 0xdb, 0x2b, 0x9b, 0x6f,
	0xce, 0x77, 0x80, 0xfe, 0xe7, 0xed, 0x37, 0x1a, 0xa8, 0x4e, 0xfa, 0x9f, 0x17, 0xff, 0x15, 0xb8,
	0x7b, 0xdf, 0x69, 0x86, 0x36, 0xad, 0xc5, 0x13, 0x46, 0x10, 0xf2, 0xbf, 0xd3, 0xa0, 0xb4, 0xbd,
	0xc9, 0x53, 0x3e, 0x85, 0x4e, 0x95, 0x4f, 0xc1, 0x14, 0x65, 0xc2, 0xd8, 0xd1, 0x68, 0x27, 0x55,
	0x70, 0xe7, 0x6e, 0x1d, 0x7d, 0x52, 0x3d, 0x94, 0x20, 0x05, 0x2b, 0x0d, 0x27, 0x09, 0xc2, 0x67,
	0xe1, 0x25, 0x04, 0xd9, 0xa6, 0x95, 0xb9, 0x2b, 0x07, 0x51, 0xfc, 0x66, 0xab, 0x83, 0x74, 0xcb,
	0x4a, 0xeb, 0x59, 0x7b, 0xc3, 0x30, 0x79, 0x79, 0xd3, 0x8b, 0x5e, 0xdd, 0xf4, 0xa2, 0xbf, 0x6f,
	0x7a, 0xd1, 0xaf, 0xb7, 0xbd, 0xb5, 0x57, 0xb7, 0xbd, 0xb5, 0x3f, 0x6f, 0x7b, 0x6b, 0xbf, 0x7c,
	0x39, 0xe5, 0xe6, 0xb2, 0x9c, 0x0c, 0xa8, 0xcc, 0xe3, 0x11, 0x1b, 0x2a, 0xa9, 0xbf, 0xbf, 0xb8,
	0xe0, 0x94, 0x93, 0x2c, 0x16, 0xcc, 0x5c, 0x49, 0x35, 0x8b, 0xe9, 0x25, 0xe1, 0x22, 0x5e, 0x54,
	0x3f, 0x13, 0xcc, 0x75, 0xc1, 0xf4, 0x64, 0xc3, 0xfe, 0xe3, 0xff, 0xfc, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x18, 0xac, 0xb9, 0x37, 0x45, 0x08, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FaucetRecipientCooldownSeconds != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.FaucetRecipientCooldownSeconds))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.FaucetEpochCap.Size()
		i -= size
		if _, err := m.FaucetEpochCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.FaucetMaxDrip.Size()
		i -= size
		if _, err := m.FaucetMaxDrip.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.FaucetEnabled {
		i--
		if m.FaucetEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.AllowBootstrapStake {
		i--
		if m.AllowBootstrapStake {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MinBlocksPerEpoch != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.MinBlocksPerEpoch))
		i--
		dAtA[i] = 0x10
	}
	if m.EpochDurationSeconds != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.EpochDurationSeconds))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EpochState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FaucetEpochMinted.Size()
		i -= size
		if _, err := m.FaucetEpochMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.CumulativeFaucetMinted.Size()
		i -= size
		if _, err := m.CumulativeFaucetMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.ValidatorSplitDelta.Size()
		i -= size
		if _, err := m.ValidatorSplitDelta.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.CumulativeServiceMinted.Size()
		i -= size
		if _, err := m.CumulativeServiceMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.CumulativeDevelopmentMinted.Size()
		i -= size
		if _, err := m.CumulativeDevelopmentMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.GenesisSupply.Size()
		i -= size
		if _, err := m.GenesisSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.CumulativeBurned.Size()
		i -= size
		if _, err := m.CumulativeBurned.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.CumulativeMinted.Size()
		i -= size
		if _, err := m.CumulativeMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.BlocksInEpoch != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.BlocksInEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochStartUnixNano != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.EpochStartUnixNano))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentEpoch != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CeilingRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CeilingRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CeilingRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DevelopmentPercent != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.DevelopmentPercent))
		i--
		dAtA[i] = 0x60
	}
	if m.RelayPercent != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.RelayPercent))
		i--
		dAtA[i] = 0x58
	}
	if m.StoragePercent != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.StoragePercent))
		i--
		dAtA[i] = 0x50
	}
	if m.ValidatorPercent != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.ValidatorPercent))
		i--
		dAtA[i] = 0x48
	}
	{
		size := m.StorageMinted.Size()
		i -= size
		if _, err := m.StorageMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.RelayMinted.Size()
		i -= size
		if _, err := m.RelayMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.DevelopmentMinted.Size()
		i -= size
		if _, err := m.DevelopmentMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.ValidatorMinted.Size()
		i -= size
		if _, err := m.ValidatorMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.DevelopmentCeiling.Size()
		i -= size
		if _, err := m.DevelopmentCeiling.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.RelayCeiling.Size()
		i -= size
		if _, err := m.RelayCeiling.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.StorageCeiling.Size()
		i -= size
		if _, err := m.StorageCeiling.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEmission(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Epoch != 0 {
		i = encodeVarintEmission(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEmission(dAtA []byte, offset int, v uint64) int {
	offset -= sovEmission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochDurationSeconds != 0 {
		n += 1 + sovEmission(uint64(m.EpochDurationSeconds))
	}
	if m.MinBlocksPerEpoch != 0 {
		n += 1 + sovEmission(uint64(m.MinBlocksPerEpoch))
	}
	if m.AllowBootstrapStake {
		n += 2
	}
	if m.FaucetEnabled {
		n += 2
	}
	l = m.FaucetMaxDrip.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.FaucetEpochCap.Size()
	n += 1 + l + sovEmission(uint64(l))
	if m.FaucetRecipientCooldownSeconds != 0 {
		n += 1 + sovEmission(uint64(m.FaucetRecipientCooldownSeconds))
	}
	return n
}

func (m *EpochState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentEpoch != 0 {
		n += 1 + sovEmission(uint64(m.CurrentEpoch))
	}
	if m.EpochStartUnixNano != 0 {
		n += 1 + sovEmission(uint64(m.EpochStartUnixNano))
	}
	if m.BlocksInEpoch != 0 {
		n += 1 + sovEmission(uint64(m.BlocksInEpoch))
	}
	l = m.CumulativeMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.CumulativeBurned.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.GenesisSupply.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.CumulativeDevelopmentMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.CumulativeServiceMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.ValidatorSplitDelta.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.CumulativeFaucetMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.FaucetEpochMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	return n
}

func (m *CeilingRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovEmission(uint64(m.Epoch))
	}
	l = m.StorageCeiling.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.RelayCeiling.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.DevelopmentCeiling.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.ValidatorMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.DevelopmentMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.RelayMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	l = m.StorageMinted.Size()
	n += 1 + l + sovEmission(uint64(l))
	if m.ValidatorPercent != 0 {
		n += 1 + sovEmission(uint64(m.ValidatorPercent))
	}
	if m.StoragePercent != 0 {
		n += 1 + sovEmission(uint64(m.StoragePercent))
	}
	if m.RelayPercent != 0 {
		n += 1 + sovEmission(uint64(m.RelayPercent))
	}
	if m.DevelopmentPercent != 0 {
		n += 1 + sovEmission(uint64(m.DevelopmentPercent))
	}
	return n
}

func sovEmission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEmission(x uint64) (n int) {
	return sovEmission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDurationSeconds", wireType)
			}
			m.EpochDurationSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochDurationSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBlocksPerEpoch", wireType)
			}
			m.MinBlocksPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinBlocksPerEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowBootstrapStake", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowBootstrapStake = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FaucetEnabled = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetMaxDrip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FaucetMaxDrip.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetEpochCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FaucetEpochCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetRecipientCooldownSeconds", wireType)
			}
			m.FaucetRecipientCooldownSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FaucetRecipientCooldownSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEmission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStartUnixNano", wireType)
			}
			m.EpochStartUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochStartUnixNano |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksInEpoch", wireType)
			}
			m.BlocksInEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksInEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CumulativeMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeBurned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CumulativeBurned.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GenesisSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeDevelopmentMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CumulativeDevelopmentMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeServiceMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CumulativeServiceMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSplitDelta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorSplitDelta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeFaucetMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CumulativeFaucetMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetEpochMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FaucetEpochMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CeilingRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CeilingRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CeilingRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageCeiling", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StorageCeiling.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayCeiling", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RelayCeiling.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevelopmentCeiling", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DevelopmentCeiling.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevelopmentMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DevelopmentMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RelayMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StorageMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorPercent", wireType)
			}
			m.ValidatorPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorPercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoragePercent", wireType)
			}
			m.StoragePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoragePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayPercent", wireType)
			}
			m.RelayPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayPercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevelopmentPercent", wireType)
			}
			m.DevelopmentPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DevelopmentPercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEmission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEmission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEmission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEmission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEmission = fmt.Errorf("proto: unexpected end of group")
)
