// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orama/cnft/v1/cnft.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Collection is one cNFT collection. Royalty is fixed at creation: a creator
// address plus a basis-point rate. There is no admin key and no message that
// changes it afterwards (plans/open-network.md D18).
type Collection struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator    string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	RoyaltyBps uint32 `protobuf:"varint,3,opt,name=royalty_bps,json=royaltyBps,proto3" json:"royalty_bps,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{0}
}
func (m *Collection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return m.Size()
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Collection) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Collection) GetRoyaltyBps() uint32 {
	if m != nil {
		return m.RoyaltyBps
	}
	return 0
}

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// ChangeLog is one entry in a tree's ring buffer of recent roots. Path[0] is
// the leaf written by that change; path[i] is the node at height i on the way
// to the root. Index is the leaf that changed.
type ChangeLog struct {
	Root  []byte   `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Path  [][]byte `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Index uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *ChangeLog) Reset()         { *m = ChangeLog{} }
func (m *ChangeLog) String() string { return proto.CompactTextString(m) }
func (*ChangeLog) ProtoMessage()    {}
func (*ChangeLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{1}
}
func (m *ChangeLog) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChangeLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChangeLog.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChangeLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeLog.Merge(m, src)
}
func (m *ChangeLog) XXX_Size() int {
	return m.Size()
}
func (m *ChangeLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeLog.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeLog proto.InternalMessageInfo

func (m *ChangeLog) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *ChangeLog) GetPath() [][]byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *ChangeLog) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

// RightmostProof is the on-chain proof of the rightmost occupied leaf. Index
// is the next append position (the tree's rightmost index). Appends use this
// path and do not need a client proof.
type RightmostProof struct {
	Proof [][]byte `protobuf:"bytes,1,rep,name=proof,proto3" json:"proof,omitempty"`
	Leaf  []byte   `protobuf:"bytes,2,opt,name=leaf,proto3" json:"leaf,omitempty"`
	Index uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *RightmostProof) Reset()         { *m = RightmostProof{} }
func (m *RightmostProof) String() string { return proto.CompactTextString(m) }
func (*RightmostProof) ProtoMessage()    {}
func (*RightmostProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{2}
}
func (m *RightmostProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RightmostProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RightmostProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RightmostProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RightmostProof.Merge(m, src)
}
func (m *RightmostProof) XXX_Size() int {
	return m.Size()
}
func (m *RightmostProof) XXX_DiscardUnknown() {
	xxx_messageInfo_RightmostProof.DiscardUnknown(m)
}

var xxx_messageInfo_RightmostProof proto.InternalMessageInfo

func (m *RightmostProof) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *RightmostProof) GetLeaf() []byte {
	if m != nil {
		return m.Leaf
	}
	return nil
}

func (m *RightmostProof) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

// Tree is one concurrent Merkle tree. State kept per tree is the current root
// (the newest changelog entry), a ring buffer of recent roots and the paths
// that produced them, and the rightmost index. Leaves themselves are not
// stored; a leaf is rebuilt from the transaction body that wrote it.
type Tree struct {
	Id           uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator      string         `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	CollectionId uint64         `protobuf:"varint,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Depth        uint32         `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	BufferSize   uint32         `protobuf:"varint,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	CanopyDepth  uint32         `protobuf:"varint,6,opt,name=canopy_depth,json=canopyDepth,proto3" json:"canopy_depth,omitempty"`
	Sequence     uint64         `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ActiveIndex  uint64         `protobuf:"varint,8,opt,name=active_index,json=activeIndex,proto3" json:"active_index,omitempty"`
	FilledBuffer uint64         `protobuf:"varint,9,opt,name=filled_buffer,json=filledBuffer,proto3" json:"filled_buffer,omitempty"`
	ChangeLogs   []ChangeLog    `protobuf:"bytes,10,rep,name=change_logs,json=changeLogs,proto3" json:"change_logs"`
	Rightmost    RightmostProof `protobuf:"bytes,11,opt,name=rightmost,proto3" json:"rightmost"`
	// canopy caches the uppermost nodes so a proof may omit them. Empty when
	// canopy_depth is 0. Indexed by heap index minus 2.
	Canopy    [][]byte `protobuf:"bytes,12,rep,name=canopy,proto3" json:"canopy,omitempty"`
	DepositId string   `protobuf:"bytes,13,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
}

func (m *Tree) Reset()         { *m = Tree{} }
func (m *Tree) String() string { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()    {}
func (*Tree) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{3}
}
func (m *Tree) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tree.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tree.Merge(m, src)
}
func (m *Tree) XXX_Size() int {
	return m.Size()
}
func (m *Tree) XXX_DiscardUnknown() {
	xxx_messageInfo_Tree.DiscardUnknown(m)
}

var xxx_messageInfo_Tree proto.InternalMessageInfo

func (m *Tree) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tree) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Tree) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *Tree) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Tree) GetBufferSize() uint32 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func (m *Tree) GetCanopyDepth() uint32 {
	if m != nil {
		return m.CanopyDepth
	}
	return 0
}

func (m *Tree) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Tree) GetActiveIndex() uint64 {
	if m != nil {
		return m.ActiveIndex
	}
	return 0
}

func (m *Tree) GetFilledBuffer() uint64 {
	if m != nil {
		return m.FilledBuffer
	}
	return 0
}

func (m *Tree) GetChangeLogs() []ChangeLog {
	if m != nil {
		return m.ChangeLogs
	}
	return nil
}

func (m *Tree) GetRightmost() RightmostProof {
	if m != nil {
		return m.Rightmost
	}
	return RightmostProof{}
}

func (m *Tree) GetCanopy() [][]byte {
	if m != nil {
		return m.Canopy
	}
	return nil
}

func (m *Tree) GetDepositId() string {
	if m != nil {
		return m.DepositId
	}
	return ""
}

// Leaf is the preimage of one compressed asset. The leaf hash is SHA-256 of
// EncodeLeaf over these fields, in this order.
type Leaf struct {
	AssetId     []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Owner       string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Delegate    string `protobuf:"bytes,3,opt,name=delegate,proto3" json:"delegate,omitempty"`
	MetadataCid string `protobuf:"bytes,4,opt,name=metadata_cid,json=metadataCid,proto3" json:"metadata_cid,omitempty"`
	CreatorHash []byte `protobuf:"bytes,5,opt,name=creator_hash,json=creatorHash,proto3" json:"creator_hash,omitempty"`
	Nonce       uint64 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	HashId      uint32 `protobuf:"varint,7,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
}

func (m *Leaf) Reset()         { *m = Leaf{} }
func (m *Leaf) String() string { return proto.CompactTextString(m) }
func (*Leaf) ProtoMessage()    {}
func (*Leaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{4}
}
func (m *Leaf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Leaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Leaf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Leaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leaf.Merge(m, src)
}
func (m *Leaf) XXX_Size() int {
	return m.Size()
}
func (m *Leaf) XXX_DiscardUnknown() {
	xxx_messageInfo_Leaf.DiscardUnknown(m)
}

var xxx_messageInfo_Leaf proto.InternalMessageInfo

func (m *Leaf) GetAssetId() []byte {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *Leaf) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Leaf) GetDelegate() string {
	if m != nil {
		return m.Delegate
	}
	return ""
}

func (m *Leaf) GetMetadataCid() string {
	if m != nil {
		return m.MetadataCid
	}
	return ""
}

func (m *Leaf) GetCreatorHash() []byte {
	if m != nil {
		return m.CreatorHash
	}
	return nil
}

func (m *Leaf) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Leaf) GetHashId() uint32 {
	if m != nil {
		return m.HashId
	}
	return 0
}

// MerkleProof authenticates a leaf against one root in the tree's changelog
// buffer. Siblings run from the leaf toward the root. The uppermost
// canopy_depth siblings may be omitted.
type MerkleProof struct {
	Root     []byte   `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Index    uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Siblings [][]byte `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
}

func (m *MerkleProof) Reset()         { *m = MerkleProof{} }
func (m *MerkleProof) String() string { return proto.CompactTextString(m) }
func (*MerkleProof) ProtoMessage()    {}
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{5}
}
func (m *MerkleProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MerkleProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MerkleProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MerkleProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleProof.Merge(m, src)
}
func (m *MerkleProof) XXX_Size() int {
	return m.Size()
}
func (m *MerkleProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleProof.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleProof proto.InternalMessageInfo

func (m *MerkleProof) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *MerkleProof) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MerkleProof) GetSiblings() [][]byte {
	if m != nil {
		return m.Siblings
	}
	return nil
}

// MintLeaf is the caller-supplied part of a new leaf. The module fills
// creator_hash, nonce and hash_id.
type MintLeaf struct {
	AssetId     []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Owner       string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Delegate    string `protobuf:"bytes,3,opt,name=delegate,proto3" json:"delegate,omitempty"`
	MetadataCid string `protobuf:"bytes,4,opt,name=metadata_cid,json=metadataCid,proto3" json:"metadata_cid,omitempty"`
}

func (m *MintLeaf) Reset()         { *m = MintLeaf{} }
func (m *MintLeaf) String() string { return proto.CompactTextString(m) }
func (*MintLeaf) ProtoMessage()    {}
func (*MintLeaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{6}
}
func (m *MintLeaf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintLeaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintLeaf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintLeaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintLeaf.Merge(m, src)
}
func (m *MintLeaf) XXX_Size() int {
	return m.Size()
}
func (m *MintLeaf) XXX_DiscardUnknown() {
	xxx_messageInfo_MintLeaf.DiscardUnknown(m)
}

var xxx_messageInfo_MintLeaf proto.InternalMessageInfo

func (m *MintLeaf) GetAssetId() []byte {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *MintLeaf) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MintLeaf) GetDelegate() string {
	if m != nil {
		return m.Delegate
	}
	return ""
}

func (m *MintLeaf) GetMetadataCid() string {
	if m != nil {
		return m.MetadataCid
	}
	return ""
}

// DecompressedAsset is the on-chain handle created by MsgDecompress. The
// compressed leaf is cleared; MsgCompress requires this owner and appends a
// new leaf.
type DecompressedAsset struct {
	AssetId      []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	TreeId       uint64 `protobuf:"varint,2,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	LeafIndex    uint32 `protobuf:"varint,3,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	Owner        string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Delegate     string `protobuf:"bytes,5,opt,name=delegate,proto3" json:"delegate,omitempty"`
	MetadataCid  string `protobuf:"bytes,6,opt,name=metadata_cid,json=metadataCid,proto3" json:"metadata_cid,omitempty"`
	CreatorHash  []byte `protobuf:"bytes,7,opt,name=creator_hash,json=creatorHash,proto3" json:"creator_hash,omitempty"`
	Nonce        uint64 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	HashId       uint32 `protobuf:"varint,9,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	CollectionId uint64 `protobuf:"varint,10,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
}

func (m *DecompressedAsset) Reset()         { *m = DecompressedAsset{} }
func (m *DecompressedAsset) String() string { return proto.CompactTextString(m) }
func (*DecompressedAsset) ProtoMessage()    {}
func (*DecompressedAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{7}
}
func (m *DecompressedAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DecompressedAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DecompressedAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DecompressedAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecompressedAsset.Merge(m, src)
}
func (m *DecompressedAsset) XXX_Size() int {
	return m.Size()
}
func (m *DecompressedAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_DecompressedAsset.DiscardUnknown(m)
}

var xxx_messageInfo_DecompressedAsset proto.InternalMessageInfo

func (m *DecompressedAsset) GetAssetId() []byte {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *DecompressedAsset) GetTreeId() uint64 {
	if m != nil {
		return m.TreeId
	}
	return 0
}

func (m *DecompressedAsset) GetLeafIndex() uint32 {
	if m != nil {
		return m.LeafIndex
	}
	return 0
}

func (m *DecompressedAsset) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DecompressedAsset) GetDelegate() string {
	if m != nil {
		return m.Delegate
	}
	return ""
}

func (m *DecompressedAsset) GetMetadataCid() string {
	if m != nil {
		return m.MetadataCid
	}
	return ""
}

func (m *DecompressedAsset) GetCreatorHash() []byte {
	if m != nil {
		return m.CreatorHash
	}
	return nil
}

func (m *DecompressedAsset) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DecompressedAsset) GetHashId() uint32 {
	if m != nil {
		return m.HashId
	}
	return 0
}

func (m *DecompressedAsset) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

// Snapshot is a content id recorded for a tree. Recording it does not open a
// storage deal.
type Snapshot struct {
	TreeId   uint64 `protobuf:"varint,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Id       uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Cid      string `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Sequence uint64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_49891f557e3e9204, []int{8}
}
func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return m.Size()
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetTreeId() uint64 {
	if m != nil {
		return m.TreeId
	}
	return 0
}

func (m *Snapshot) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Snapshot) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Snapshot) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*Collection)(nil), "orama.cnft.v1.Collection")
	proto.RegisterType((*ChangeLog)(nil), "orama.cnft.v1.ChangeLog")
	proto.RegisterType((*RightmostProof)(nil), "orama.cnft.v1.RightmostProof")
	proto.RegisterType((*Tree)(nil), "orama.cnft.v1.Tree")
	proto.RegisterType((*Leaf)(nil), "orama.cnft.v1.Leaf")
	proto.RegisterType((*MerkleProof)(nil), "orama.cnft.v1.MerkleProof")
	proto.RegisterType((*MintLeaf)(nil), "orama.cnft.v1.MintLeaf")
	proto.RegisterType((*DecompressedAsset)(nil), "orama.cnft.v1.DecompressedAsset")
	proto.RegisterType((*Snapshot)(nil), "orama.cnft.v1.Snapshot")
}

func init() { proto.RegisterFile("orama/cnft/v1/cnft.proto", fileDescriptor_49891f557e3e9204) }

var fileDescriptor_49891f557e3e9204 = []byte{
	// 781 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x35, 0x25, 0x5a, 0x12, 0x87, 0x52, 0xd0, 0x12, 0x41, 0xc3, 0x06, 0x88, 0xa2, 0xb2, 0x17,
	0x9d, 0x24, 0x24, 0xed, 0xbd, 0x88, 0xec, 0x43, 0x05, 0x24, 0xad, 0x41, 0xf7, 0xd4, 0x0b, 0xb1,
	0xe2, 0x0e, 0xc9, 0x85, 0x29, 0x2e, 0xcb, 0x5d, 0x3b, 0xb1, 0xbf, 0xa2, 0xdf, 0xd2, 0xaf, 0xf0,
	0xa9, 0xc8, 0xb1, 0xa7, 0xa2, 0xb0, 0x7f, 0xa4, 0xd8, 0x59, 0x8a, 0xb1, 0x6a, 0x38, 0x41, 0x4f,
	0x39, 0x69, 0xde, 0xdb, 0x9d, 0xdd, 0xd1, 0x7b, 0xb3, 0x43, 0x08, 0x65, 0xc3, 0xb6, 0x6c, 0x99,
	0x56, 0x99, 0x5e, 0x5e, 0xbc, 0xa0, 0xdf, 0x45, 0xdd, 0x48, 0x2d, 0x83, 0x09, 0xad, 0x2c, 0x88,
	0xb9, 0x78, 0xf1, 0xf4, 0x71, 0x2e, 0x73, 0x49, 0x2b, 0x4b, 0x13, 0xd9, 0x4d, 0xd1, 0x19, 0xc0,
	0x91, 0x2c, 0x4b, 0x4c, 0xb5, 0x90, 0x55, 0xf0, 0x08, 0x7a, 0x82, 0x87, 0xce, 0xcc, 0x99, 0xbb,
	0x71, 0x4f, 0xf0, 0x20, 0x84, 0x61, 0xda, 0x20, 0xd3, 0xb2, 0x09, 0x7b, 0x33, 0x67, 0xee, 0xc5,
	0x3b, 0x18, 0x3c, 0x07, 0xbf, 0x91, 0x97, 0xac, 0xd4, 0x97, 0xc9, 0xa6, 0x56, 0x61, 0x7f, 0xe6,
	0xcc, 0x27, 0x31, 0xb4, 0xd4, 0xaa, 0x56, 0x41, 0x00, 0x6e, 0xc5, 0xb6, 0x18, 0xba, 0x94, 0x47,
	0x71, 0xb4, 0x06, 0xef, 0xa8, 0x60, 0x55, 0x8e, 0xaf, 0x65, 0x6e, 0x36, 0x34, 0x52, 0x6a, 0xba,
	0x6d, 0x1c, 0x53, 0x6c, 0xb8, 0x9a, 0xe9, 0x22, 0xec, 0xcd, 0xfa, 0x86, 0x33, 0x71, 0xf0, 0x18,
	0x0e, 0x45, 0xc5, 0xf1, 0x5d, 0x7b, 0x87, 0x05, 0xd1, 0x09, 0x3c, 0x8a, 0x45, 0x5e, 0xe8, 0xad,
	0x54, 0xfa, 0xa4, 0x91, 0x32, 0x33, 0xfb, 0x6a, 0x13, 0x84, 0x0e, 0x25, 0x5b, 0x60, 0x4e, 0x2c,
	0x91, 0x65, 0x54, 0xfe, 0x38, 0xa6, 0xf8, 0x81, 0x13, 0xff, 0xec, 0x83, 0xfb, 0x4b, 0x83, 0xf8,
	0x3f, 0x44, 0xf8, 0x16, 0x26, 0x69, 0x27, 0x5e, 0x22, 0x38, 0x1d, 0xe8, 0xc6, 0xe3, 0x0f, 0xe4,
	0x9a, 0x9b, 0xdb, 0x38, 0xd6, 0xba, 0x20, 0x25, 0x26, 0xb1, 0x05, 0x46, 0xbf, 0xcd, 0x79, 0x96,
	0x61, 0x93, 0x28, 0x71, 0x85, 0xe1, 0xa1, 0xd5, 0xcf, 0x52, 0xa7, 0xe2, 0x0a, 0x83, 0x6f, 0x60,
	0x9c, 0xb2, 0x4a, 0xd6, 0x97, 0x89, 0xcd, 0x1e, 0xd0, 0x0e, 0xdf, 0x72, 0xc7, 0x74, 0xc6, 0x53,
	0x18, 0x29, 0xfc, 0xed, 0x1c, 0xab, 0x14, 0xc3, 0x21, 0xdd, 0xdc, 0x61, 0x93, 0xce, 0x52, 0x2d,
	0x2e, 0x30, 0xb1, 0x7f, 0x75, 0x44, 0xeb, 0xbe, 0xe5, 0xd6, 0x86, 0x32, 0xd5, 0x67, 0xa2, 0x2c,
	0x91, 0x27, 0xf6, 0xda, 0xd0, 0xb3, 0xd5, 0x5b, 0x72, 0x45, 0x5c, 0xf0, 0x03, 0xf8, 0x29, 0x59,
	0x96, 0x94, 0x32, 0x57, 0x21, 0xcc, 0xfa, 0x73, 0xff, 0x65, 0xb8, 0xd8, 0x6b, 0xad, 0x45, 0x67,
	0xea, 0xca, 0xbd, 0xfe, 0xfb, 0xf9, 0x41, 0x0c, 0xe9, 0x8e, 0x50, 0xc1, 0x2b, 0xf0, 0x9a, 0x9d,
	0x51, 0xa1, 0x3f, 0x73, 0xe6, 0xfe, 0xcb, 0x67, 0xff, 0x49, 0xdf, 0x37, 0xb2, 0x3d, 0xe3, 0x43,
	0x56, 0xf0, 0x15, 0x0c, 0xec, 0xdf, 0x0e, 0xc7, 0x64, 0x6d, 0x8b, 0x82, 0x67, 0x00, 0x1c, 0x6b,
	0xa9, 0x84, 0x36, 0xda, 0x4f, 0xc8, 0x1b, 0xaf, 0x65, 0xd6, 0x3c, 0xba, 0x76, 0xc0, 0x7d, 0x6d,
	0xfc, 0xfe, 0x1a, 0x46, 0x4c, 0x29, 0xa4, 0x5d, 0xb6, 0xdb, 0x86, 0x84, 0xad, 0x39, 0xf2, 0x6d,
	0x85, 0x3b, 0x67, 0x2d, 0x30, 0xc2, 0x72, 0x2c, 0x31, 0x67, 0x1a, 0xc9, 0x52, 0x2f, 0xee, 0xb0,
	0x11, 0x76, 0x8b, 0x9a, 0x71, 0xa6, 0x59, 0x92, 0x0a, 0xde, 0xf6, 0xb7, 0xbf, 0xe3, 0x8e, 0x04,
	0x27, 0xeb, 0x6c, 0x87, 0x24, 0x05, 0x53, 0x05, 0x99, 0x3b, 0x8e, 0xfd, 0x96, 0xfb, 0x91, 0x29,
	0x6a, 0xea, 0x4a, 0x1a, 0xdf, 0x06, 0xa4, 0xb9, 0x05, 0xc1, 0x13, 0x18, 0x9a, 0x04, 0x53, 0xe7,
	0x90, 0xec, 0x1e, 0x18, 0xb8, 0xe6, 0xd1, 0x29, 0xf8, 0x6f, 0xb0, 0x39, 0x2b, 0xf1, 0x64, 0xd7,
	0xd4, 0xf7, 0x9e, 0x4e, 0xd7, 0xd4, 0xbd, 0x3b, 0x4d, 0x4d, 0x2d, 0x22, 0x36, 0xa5, 0xa8, 0x72,
	0xf3, 0x46, 0x8d, 0x78, 0x1d, 0x8e, 0xae, 0x60, 0xf4, 0x46, 0x54, 0xfa, 0x73, 0x48, 0x14, 0xfd,
	0xd1, 0x83, 0x2f, 0x8f, 0x31, 0x95, 0xdb, 0xba, 0x41, 0xa5, 0x90, 0xbf, 0x32, 0x97, 0x7d, 0xac,
	0x8a, 0x27, 0x30, 0xd4, 0x0d, 0xa2, 0x59, 0xe9, 0x91, 0x64, 0x03, 0x03, 0xd7, 0xdc, 0x34, 0x81,
	0x79, 0xd4, 0xc9, 0xdd, 0x17, 0xed, 0x19, 0xc6, 0x36, 0x79, 0x57, 0xbd, 0xfb, 0x50, 0xf5, 0x87,
	0x9f, 0xa8, 0x7e, 0xf0, 0x69, 0x83, 0x87, 0x1f, 0x31, 0x78, 0xf4, 0x80, 0xc1, 0xde, 0x5d, 0x83,
	0xef, 0x4f, 0x12, 0xb8, 0x3f, 0x49, 0x22, 0x06, 0xa3, 0xd3, 0x8a, 0xd5, 0xaa, 0x90, 0xfa, 0xae,
	0x1e, 0xce, 0x9e, 0x1e, 0x76, 0x7a, 0xf5, 0xba, 0xe9, 0xf5, 0x05, 0xf4, 0xd3, 0x76, 0x32, 0x79,
	0xb1, 0x09, 0xf7, 0xc6, 0x86, 0xbb, 0x3f, 0x36, 0x56, 0x3f, 0x5d, 0xdf, 0x4c, 0x9d, 0xf7, 0x37,
	0x53, 0xe7, 0x9f, 0x9b, 0xa9, 0xf3, 0xfb, 0xed, 0xf4, 0xe0, 0xfd, 0xed, 0xf4, 0xe0, 0xaf, 0xdb,
	0xe9, 0xc1, 0xaf, 0xdf, 0xe7, 0x42, 0x17, 0xe7, 0x9b, 0x45, 0x2a, 0xb7, 0xcb, 0x63, 0x5c, 0x35,
	0x52, 0xfd, 0x9c, 0x65, 0x22, 0x15, 0xac, 0x5c, 0x56, 0xa8, 0xdf, 0xca, 0xe6, 0x6c, 0x99, 0x16,
	0x4c, 0x54, 0xcb, 0x77, 0xf6, 0x5b, 0xa4, 0x2f, 0x6b, 0x54, 0x9b, 0x01, 0x7d, 0x65, 0xbe, 0xfb,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x94, 0xf5, 0x7d, 0x17, 0xa6, 0x06, 0x00, 0x00,
}

func (m *Collection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Collection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Collection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if m.RoyaltyBps != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.RoyaltyBps))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ChangeLog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChangeLog) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChangeLog) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Path) > 0 {
		for iNdEx := len(m.Path) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Path[iNdEx])
			copy(dAtA[i:], m.Path[iNdEx])
			i = encodeVarintCnft(dAtA, i, uint64(len(m.Path[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RightmostProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RightmostProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RightmostProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Leaf) > 0 {
		i -= len(m.Leaf)
		copy(dAtA[i:], m.Leaf)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Leaf)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Proof) > 0 {
		for iNdEx := len(m.Proof) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Proof[iNdEx])
			copy(dAtA[i:], m.Proof[iNdEx])
			i = encodeVarintCnft(dAtA, i, uint64(len(m.Proof[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Tree) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tree) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tree) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepositId) > 0 {
		i -= len(m.DepositId)
		copy(dAtA[i:], m.DepositId)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.DepositId)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Canopy) > 0 {
		for iNdEx := len(m.Canopy) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Canopy[iNdEx])
			copy(dAtA[i:], m.Canopy[iNdEx])
			i = encodeVarintCnft(dAtA, i, uint64(len(m.Canopy[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	{
		size, err := m.Rightmost.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCnft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if len(m.ChangeLogs) > 0 {
		for iNdEx := len(m.ChangeLogs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChangeLogs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCnft(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.FilledBuffer != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.FilledBuffer))
		i--
		dAtA[i] = 0x48
	}
	if m.ActiveIndex != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.ActiveIndex))
		i--
		dAtA[i] = 0x40
	}
	if m.Sequence != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x38
	}
	if m.CanopyDepth != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.CanopyDepth))
		i--
		dAtA[i] = 0x30
	}
	if m.BufferSize != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.BufferSize))
		i--
		dAtA[i] = 0x28
	}
	if m.Depth != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Depth))
		i--
		dAtA[i] = 0x20
	}
	if m.CollectionId != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Leaf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Leaf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Leaf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HashId != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.HashId))
		i--
		dAtA[i] = 0x38
	}
	if m.Nonce != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x30
	}
	if len(m.CreatorHash) > 0 {
		i -= len(m.CreatorHash)
		copy(dAtA[i:], m.CreatorHash)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.CreatorHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MetadataCid) > 0 {
		i -= len(m.MetadataCid)
		copy(dAtA[i:], m.MetadataCid)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.MetadataCid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Delegate) > 0 {
		i -= len(m.Delegate)
		copy(dAtA[i:], m.Delegate)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Delegate)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MerkleProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MerkleProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MerkleProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Siblings) > 0 {
		for iNdEx := len(m.Siblings) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Siblings[iNdEx])
			copy(dAtA[i:], m.Siblings[iNdEx])
			i = encodeVarintCnft(dAtA, i, uint64(len(m.Siblings[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Index != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MintLeaf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintLeaf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintLeaf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataCid) > 0 {
		i -= len(m.MetadataCid)
		copy(dAtA[i:], m.MetadataCid)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.MetadataCid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Delegate) > 0 {
		i -= len(m.Delegate)
		copy(dAtA[i:], m.Delegate)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Delegate)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DecompressedAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DecompressedAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DecompressedAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CollectionId != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.CollectionId))
		i--
		dAtA[i] = 0x50
	}
	if m.HashId != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.HashId))
		i--
		dAtA[i] = 0x48
	}
	if m.Nonce != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CreatorHash) > 0 {
		i -= len(m.CreatorHash)
		copy(dAtA[i:], m.CreatorHash)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.CreatorHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MetadataCid) > 0 {
		i -= len(m.MetadataCid)
		copy(dAtA[i:], m.MetadataCid)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.MetadataCid)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Delegate) > 0 {
		i -= len(m.Delegate)
		copy(dAtA[i:], m.Delegate)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Delegate)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if m.LeafIndex != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.LeafIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.TreeId != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.TreeId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Snapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Snapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Snapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintCnft(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if m.TreeId != 0 {
		i = encodeVarintCnft(dAtA, i, uint64(m.TreeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCnft(dAtA []byte, offset int, v uint64) int {
	offset -= sovCnft(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Collection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCnft(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.RoyaltyBps != 0 {
		n += 1 + sovCnft(uint64(m.RoyaltyBps))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	return n
}

func (m *ChangeLog) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if len(m.Path) > 0 {
		for _, b := range m.Path {
			l = len(b)
			n += 1 + l + sovCnft(uint64(l))
		}
	}
	if m.Index != 0 {
		n += 1 + sovCnft(uint64(m.Index))
	}
	return n
}

func (m *RightmostProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Proof) > 0 {
		for _, b := range m.Proof {
			l = len(b)
			n += 1 + l + sovCnft(uint64(l))
		}
	}
	l = len(m.Leaf)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovCnft(uint64(m.Index))
	}
	return n
}

func (m *Tree) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCnft(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.CollectionId != 0 {
		n += 1 + sovCnft(uint64(m.CollectionId))
	}
	if m.Depth != 0 {
		n += 1 + sovCnft(uint64(m.Depth))
	}
	if m.BufferSize != 0 {
		n += 1 + sovCnft(uint64(m.BufferSize))
	}
	if m.CanopyDepth != 0 {
		n += 1 + sovCnft(uint64(m.CanopyDepth))
	}
	if m.Sequence != 0 {
		n += 1 + sovCnft(uint64(m.Sequence))
	}
	if m.ActiveIndex != 0 {
		n += 1 + sovCnft(uint64(m.ActiveIndex))
	}
	if m.FilledBuffer != 0 {
		n += 1 + sovCnft(uint64(m.FilledBuffer))
	}
	if len(m.ChangeLogs) > 0 {
		for _, e := range m.ChangeLogs {
			l = e.Size()
			n += 1 + l + sovCnft(uint64(l))
		}
	}
	l = m.Rightmost.Size()
	n += 1 + l + sovCnft(uint64(l))
	if len(m.Canopy) > 0 {
		for _, b := range m.Canopy {
			l = len(b)
			n += 1 + l + sovCnft(uint64(l))
		}
	}
	l = len(m.DepositId)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	return n
}

func (m *Leaf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.Delegate)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.MetadataCid)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.CreatorHash)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovCnft(uint64(m.Nonce))
	}
	if m.HashId != 0 {
		n += 1 + sovCnft(uint64(m.HashId))
	}
	return n
}

func (m *MerkleProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovCnft(uint64(m.Index))
	}
	if len(m.Siblings) > 0 {
		for _, b := range m.Siblings {
			l = len(b)
			n += 1 + l + sovCnft(uint64(l))
		}
	}
	return n
}

func (m *MintLeaf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.Delegate)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.MetadataCid)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	return n
}

func (m *DecompressedAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.TreeId != 0 {
		n += 1 + sovCnft(uint64(m.TreeId))
	}
	if m.LeafIndex != 0 {
		n += 1 + sovCnft(uint64(m.LeafIndex))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.Delegate)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.MetadataCid)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	l = len(m.CreatorHash)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovCnft(uint64(m.Nonce))
	}
	if m.HashId != 0 {
		n += 1 + sovCnft(uint64(m.HashId))
	}
	if m.CollectionId != 0 {
		n += 1 + sovCnft(uint64(m.CollectionId))
	}
	return n
}

func (m *Snapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TreeId != 0 {
		n += 1 + sovCnft(uint64(m.TreeId))
	}
	if m.Id != 0 {
		n += 1 + sovCnft(uint64(m.Id))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovCnft(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovCnft(uint64(m.Sequence))
	}
	return n
}

func sovCnft(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCnft(x uint64) (n int) {
	return sovCnft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Collection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Collection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Collection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoyaltyBps", wireType)
			}
			m.RoyaltyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoyaltyBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChangeLog) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChangeLog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChangeLog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = append(m.Path, make([]byte, postIndex-iNdEx))
			copy(m.Path[len(m.Path)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RightmostProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RightmostProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RightmostProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof, make([]byte, postIndex-iNdEx))
			copy(m.Proof[len(m.Proof)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaf", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leaf = append(m.Leaf[:0], dAtA[iNdEx:postIndex]...)
			if m.Leaf == nil {
				m.Leaf = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tree) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tree: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tree: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depth", wireType)
			}
			m.Depth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Depth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferSize", wireType)
			}
			m.BufferSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BufferSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanopyDepth", wireType)
			}
			m.CanopyDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CanopyDepth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveIndex", wireType)
			}
			m.ActiveIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilledBuffer", wireType)
			}
			m.FilledBuffer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FilledBuffer |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeLogs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChangeLogs = append(m.ChangeLogs, ChangeLog{})
			if err := m.ChangeLogs[len(m.ChangeLogs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rightmost", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rightmost.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Canopy", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Canopy = append(m.Canopy, make([]byte, postIndex-iNdEx))
			copy(m.Canopy[len(m.Canopy)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Leaf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Leaf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Leaf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = append(m.AssetId[:0], dAtA[iNdEx:postIndex]...)
			if m.AssetId == nil {
				m.AssetId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorHash = append(m.CreatorHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CreatorHash == nil {
				m.CreatorHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashId", wireType)
			}
			m.HashId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HashId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MerkleProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MerkleProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MerkleProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Siblings", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Siblings = append(m.Siblings, make([]byte, postIndex-iNdEx))
			copy(m.Siblings[len(m.Siblings)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MintLeaf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintLeaf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintLeaf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = append(m.AssetId[:0], dAtA[iNdEx:postIndex]...)
			if m.AssetId == nil {
				m.AssetId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DecompressedAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DecompressedAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DecompressedAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = append(m.AssetId[:0], dAtA[iNdEx:postIndex]...)
			if m.AssetId == nil {
				m.AssetId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeId", wireType)
			}
			m.TreeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeafIndex", wireType)
			}
			m.LeafIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeafIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorHash = append(m.CreatorHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CreatorHash == nil {
				m.CreatorHash = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashId", wireType)
			}
			m.HashId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HashId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			m.CollectionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Snapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Snapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Snapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeId", wireType)
			}
			m.TreeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCnft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCnft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCnft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCnft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCnft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCnft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCnft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCnft
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCnft
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCnft
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCnft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCnft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCnft = fmt.Errorf("proto: unexpected end of group")
)
