package types

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// submitProofsWireHex is MsgSubmitProofs for the body below. core's
// EncodeProofs must produce the same bytes.
const submitProofsWireHex = "0a2c6f72616d613139726c34636d32686d7238616679346b6c6470787a33666b61346a677571306135747570307312066e6f64652d611aab08080710021803228008abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab2a20cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"

func TestMsgSubmitProofs_wireMatchesCoreEncoder(t *testing.T) {
	msg := &MsgSubmitProofs{
		Signer: "orama19rl4cm2hmr8afy4kldpxz3fka4jguq0a5tup0s",
		NodeId: "node-a",
		Proofs: []ReplicaProof{{
			DealId:    7,
			Slot:      2,
			LeafIndex: 3,
			Leaf:      bytes.Repeat([]byte{0xab}, 1024),
			Siblings:  [][]byte{bytes.Repeat([]byte{0xcd}, 32)},
		}},
	}
	got, err := msg.Marshal()
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(got) != submitProofsWireHex {
		t.Fatalf("wire %x", got)
	}
}
