// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orama/nodes/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState is x/nodes' genesis state. The bank genesis must already
// hold bonds + unbonding norama in the nodes module account; InitGenesis
// checks that and does not mint.
type GenesisState struct {
	Params         Params           `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Operators      []Operator       `protobuf:"bytes,2,rep,name=operators,proto3" json:"operators"`
	Nodes          []Node           `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes"`
	Clusters       []Cluster        `protobuf:"bytes,4,rep,name=clusters,proto3" json:"clusters"`
	Unbondings     []UnbondingEntry `protobuf:"bytes,5,rep,name=unbondings,proto3" json:"unbondings"`
	RevokedPubkeys []RevokedPubkey  `protobuf:"bytes,6,rep,name=revoked_pubkeys,json=revokedPubkeys,proto3" json:"revoked_pubkeys"`
	ServiceDays    []ServiceDay     `protobuf:"bytes,7,rep,name=service_days,json=serviceDays,proto3" json:"service_days"`
	// next_unbonding_id is the next id the unbonding queue will assign.
	// Zero means the queue has never issued an id.
	NextUnbondingId uint64     `protobuf:"varint,8,opt,name=next_unbonding_id,json=nextUnbondingId,proto3" json:"next_unbonding_id,omitempty"`
	NodeNames       []NodeName `protobuf:"bytes,9,rep,name=node_names,json=nodeNames,proto3" json:"node_names"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3265266ffc4243, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetOperators() []Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

func (m *GenesisState) GetNodes() []Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GenesisState) GetClusters() []Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func (m *GenesisState) GetUnbondings() []UnbondingEntry {
	if m != nil {
		return m.Unbondings
	}
	return nil
}

func (m *GenesisState) GetRevokedPubkeys() []RevokedPubkey {
	if m != nil {
		return m.RevokedPubkeys
	}
	return nil
}

func (m *GenesisState) GetServiceDays() []ServiceDay {
	if m != nil {
		return m.ServiceDays
	}
	return nil
}

func (m *GenesisState) GetNextUnbondingId() uint64 {
	if m != nil {
		return m.NextUnbondingId
	}
	return 0
}

func (m *GenesisState) GetNodeNames() []NodeName {
	if m != nil {
		return m.NodeNames
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "orama.nodes.v1.GenesisState")
}

func init() { proto.RegisterFile("orama/nodes/v1/genesis.proto", fileDescriptor_fb3265266ffc4243) }

var fileDescriptor_fb3265266ffc4243 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x1b, 0xd6, 0x95, 0xd5, 0x9d, 0x36, 0x61, 0x4d, 0x60, 0x55, 0x10, 0x2a, 0x4e, 0x15,
	0x87, 0x98, 0x0d, 0x38, 0x20, 0xc1, 0xa5, 0x2b, 0x42, 0x48, 0x68, 0x9d, 0x3a, 0x71, 0xe1, 0x12,
	0xb9, 0xc9, 0xb7, 0xcc, 0xea, 0x62, 0x47, 0xfe, 0xdc, 0xb2, 0xbe, 0x05, 0xef, 0xc2, 0x4b, 0xec,
	0xb8, 0x23, 0x27, 0x84, 0xda, 0x17, 0x41, 0x75, 0xdc, 0x50, 0xa2, 0xdd, 0x12, 0xff, 0x7f, 0xbf,
	0x7f, 0x92, 0x2f, 0x1f, 0x79, 0xaa, 0x8d, 0xc8, 0x05, 0x57, 0x3a, 0x05, 0xe4, 0xf3, 0x63, 0x9e,
	0x81, 0x02, 0x94, 0x18, 0x15, 0x46, 0x5b, 0x4d, 0x0f, 0x5c, 0x1a, 0xb9, 0x34, 0x9a, 0x1f, 0x77,
	0x8f, 0x32, 0x9d, 0x69, 0x17, 0xf1, 0xf5, 0x55, 0x49, 0x75, 0xbb, 0xb5, 0x8e, 0x12, 0x77, 0xd9,
	0x8b, 0x9f, 0x4d, 0xb2, 0xff, 0xa9, 0xec, 0xbc, 0xb0, 0xc2, 0x02, 0x7d, 0x43, 0x5a, 0x85, 0x30,
	0x22, 0x47, 0x16, 0xf4, 0x82, 0x7e, 0xe7, 0xe4, 0x71, 0xf4, 0xff, 0x33, 0xa2, 0x73, 0x97, 0x0e,
	0x9a, 0xb7, 0xbf, 0x9f, 0x37, 0xc6, 0x9e, 0xa5, 0xef, 0x49, 0x5b, 0x17, 0x60, 0x84, 0xd5, 0x06,
	0xd9, 0x83, 0xde, 0x4e, 0xbf, 0x73, 0xc2, 0xea, 0xe2, 0xc8, 0x03, 0x5e, 0xfd, 0x27, 0xd0, 0x57,
	0x64, 0xd7, 0x51, 0x6c, 0xc7, 0x99, 0x47, 0x75, 0xf3, 0x4c, 0xa7, 0xe0, 0xad, 0x12, 0xa4, 0xef,
	0xc8, 0x5e, 0x72, 0x3d, 0x43, 0x0b, 0x06, 0x59, 0xd3, 0x49, 0x4f, 0xea, 0xd2, 0x69, 0x99, 0x7b,
	0xaf, 0xc2, 0xe9, 0x90, 0x90, 0x99, 0x9a, 0x68, 0x95, 0x4a, 0x95, 0x21, 0xdb, 0x75, 0x72, 0x58,
	0x97, 0xbf, 0x6e, 0x88, 0x8f, 0xca, 0x9a, 0x85, 0xef, 0xd8, 0xf2, 0xe8, 0x17, 0x72, 0x68, 0x60,
	0xae, 0xa7, 0x90, 0xc6, 0xc5, 0x6c, 0x32, 0x85, 0x05, 0xb2, 0x96, 0xab, 0x7a, 0x56, 0xaf, 0x1a,
	0x97, 0xd8, 0xb9, 0xa3, 0x7c, 0xd3, 0x81, 0xd9, 0x3e, 0x44, 0x7a, 0x4a, 0xf6, 0x11, 0xcc, 0x5c,
	0x26, 0x10, 0xa7, 0x62, 0x81, 0xec, 0xa1, 0xab, 0xea, 0xd6, 0xab, 0x2e, 0x4a, 0x66, 0x28, 0x36,
	0x3d, 0x1d, 0xac, 0x4e, 0x90, 0xbe, 0x24, 0x8f, 0x14, 0xdc, 0xd8, 0xb8, 0x7a, 0xcb, 0x58, 0xa6,
	0x6c, 0xaf, 0x17, 0xf4, 0x9b, 0xe3, 0xc3, 0x75, 0x50, 0x7d, 0xd3, 0xe7, 0x94, 0x7e, 0x20, 0x64,
	0xdd, 0x1a, 0x2b, 0x91, 0x03, 0xb2, 0xf6, 0xfd, 0x3f, 0x6c, 0x3d, 0xf6, 0x33, 0x91, 0x6f, 0x46,
	0xdf, 0x56, 0xfe, 0x1e, 0x07, 0xa3, 0xdb, 0x65, 0x18, 0xdc, 0x2d, 0xc3, 0xe0, 0xcf, 0x32, 0x0c,
	0x7e, 0xac, 0xc2, 0xc6, 0xdd, 0x2a, 0x6c, 0xfc, 0x5a, 0x85, 0x8d, 0x6f, 0x6f, 0x33, 0x69, 0xaf,
	0x66, 0x93, 0x28, 0xd1, 0x39, 0x1f, 0xc2, 0xc0, 0x68, 0x1c, 0x5d, 0x5e, 0xca, 0x44, 0x8a, 0x6b,
	0xae, 0xc0, 0x7e, 0xd7, 0x66, 0xca, 0x93, 0x2b, 0x21, 0x15, 0xbf, 0xf1, 0xfb, 0x68, 0x17, 0x05,
	0xe0, 0xa4, 0xe5, 0xb6, 0xf1, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0xe8, 0xe8, 0xde,
	0xef, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeNames) > 0 {
		for iNdEx := len(m.NodeNames) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NodeNames[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.NextUnbondingId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextUnbondingId))
		i--
		dAtA[i] = 0x40
	}
	if len(m.ServiceDays) > 0 {
		for iNdEx := len(m.ServiceDays) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ServiceDays[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.RevokedPubkeys) > 0 {
		for iNdEx := len(m.RevokedPubkeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RevokedPubkeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Unbondings) > 0 {
		for iNdEx := len(m.Unbondings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Unbondings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Clusters) > 0 {
		for iNdEx := len(m.Clusters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Clusters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Operators) > 0 {
		for iNdEx := len(m.Operators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Operators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Operators) > 0 {
		for _, e := range m.Operators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Clusters) > 0 {
		for _, e := range m.Clusters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Unbondings) > 0 {
		for _, e := range m.Unbondings {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RevokedPubkeys) > 0 {
		for _, e := range m.RevokedPubkeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ServiceDays) > 0 {
		for _, e := range m.ServiceDays {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextUnbondingId != 0 {
		n += 1 + sovGenesis(uint64(m.NextUnbondingId))
	}
	if len(m.NodeNames) > 0 {
		for _, e := range m.NodeNames {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operators = append(m.Operators, Operator{})
			if err := m.Operators[len(m.Operators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, Node{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Clusters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Clusters = append(m.Clusters, Cluster{})
			if err := m.Clusters[len(m.Clusters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unbondings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Unbondings = append(m.Unbondings, UnbondingEntry{})
			if err := m.Unbondings[len(m.Unbondings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedPubkeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevokedPubkeys = append(m.RevokedPubkeys, RevokedPubkey{})
			if err := m.RevokedPubkeys[len(m.RevokedPubkeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceDays", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceDays = append(m.ServiceDays, ServiceDay{})
			if err := m.ServiceDays[len(m.ServiceDays)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextUnbondingId", wireType)
			}
			m.NextUnbondingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextUnbondingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeNames", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeNames = append(m.NodeNames, NodeName{})
			if err := m.NodeNames[len(m.NodeNames)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
